import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { configuredWakePhrases, extractWisdoWakeCommand, WisdoIntentService, validateStructuredIntent } from '../services/wisdoIntentService.js';
import { WisdoSafetyService } from '../services/wisdoSafetyService.js';
import { confirmationActionHash } from '../services/wisdoConfirmationService.js';
import { defaultDailyPlan, validateDailyPlan, WisdoPlanService } from '../services/wisdoPlanService.js';
import { WisdoExecutionService } from '../services/wisdoExecutionService.js';
import { WisdoPlanMonitorService } from '../services/wisdoPlanMonitorService.js';
import { WisdoDeviceService } from '../services/wisdoDeviceService.js';
import { COACH_RESPONSES, WisdoConversationService } from '../services/wisdoConversationService.js';

const intents=new WisdoIntentService();
const safety=new WisdoSafetyService();
const planService=new WisdoPlanService();
const migration=fs.readFileSync(new URL('../migrations/2026-08-09-conversational-trading-os.sql',import.meta.url),'utf8');
const routes=fs.readFileSync(new URL('../server/conversationalVoiceRoutes.js',import.meta.url),'utf8');
const mt4=fs.readFileSync(new URL('../services/mt4CommandService.js',import.meta.url),'utf8');

test('1 wake-word recognition',()=>assert.equal(extractWisdoWakeCommand('Hey Coach, status').command,'status'));
test('2 wake-word variations',()=>{for(const word of ['Hey Wisdom','Hey Wisdo','Wizzo','Wise Doe','Trading Assistant'])assert.equal(extractWisdoWakeCommand(`${word}!`).matched,true);});
test('3 wake vocabulary is configurable',()=>assert.ok(configuredWakePhrases('coach prime').includes('coach prime')));
test('4 wake-only mandatory response is exact',()=>assert.equal(COACH_RESPONSES.wake,"I'm listening. What can I help you with?"));
test('5 idle-ready response is exact',()=>assert.equal(COACH_RESPONSES.ready,'What else can I help you with today?'));
test('6 unsupported fallback promises no change',()=>assert.match(COACH_RESPONSES.unsupported,/did not make any changes/));
test('7 processing failure fallback promises no change',()=>assert.match(COACH_RESPONSES.failed,/have not changed your trading setup/));
test('8 offline response promises no application',()=>assert.match(COACH_RESPONSES.offline,/offline.*did not apply/is));
test('9 natural pause intent',()=>assert.equal(intents.deterministic('Please pause trading').commandName,'STOP_ENTRIES'));
test('10 close all intent is structured',()=>assert.deepEqual(intents.deterministic('close all trades').parameters,{}));
test('11 intent schema validates strict action',()=>assert.equal(validateStructuredIntent(intents.deterministic('close all trades')).ok,true));
test('12 intent schema rejects raw text',()=>assert.equal(validateStructuredIntent('close all').ok,false));
test('12b intent schema rejects unregistered model commands',()=>assert.equal(validateStructuredIntent({type:'ACTION',intent:'DO_THING',commandName:'RAW_MT4_TEXT',parameters:{},confidence:.9}).ok,false));
test('13 low confidence risk asks for value',()=>assert.ok(intents.deterministic('set risk percent').confidence<0.72));
test('14 buy-only routes to Reporter v1.59 globals handler',()=>{const parsed=intents.deterministic('only allow buys');assert.equal(parsed.intent,'BUY_ONLY');assert.equal(parsed.commandName,'CEM_SET_GLOBALS');});
test('14b guard mode uses the protected canonical command path',()=>{const parsed=intents.deterministic('put my account in Guard Mode');assert.equal(parsed.intent,'GUARD_MODE');assert.equal(parsed.commandName,'SET_CONTROL_MODE');assert.equal(parsed.parameters.allowNewTrades,false);});
test('15 sell-only routes to Reporter v1.59 globals handler',()=>{const parsed=intents.deterministic('block buys');assert.equal(parsed.intent,'SELL_ONLY');assert.equal(parsed.commandName,'CEM_SET_GLOBALS');});
test('16 both directions routes to Reporter v1.59 globals handler',()=>{const parsed=intents.deterministic('allow buys and sells');assert.equal(parsed.intent,'BOTH_DIRECTIONS');assert.equal(parsed.commandName,'CEM_SET_GLOBALS');});
test('17 fixed lot is deterministic',()=>assert.equal(intents.deterministic('set fixed lot to .05').parameters.globals.WISDO_FIXED_LOT,.05));
test('18 maximum trades is deterministic',()=>assert.equal(intents.deterministic('set maximum trades to 5').parameters.globals.WISDO_MAX_TRADES,5));
test('19 daily plan activation phrase',()=>assert.equal(intents.deterministic("let's build today's trading plan").intent,'CREATE_DAILY_PLAN'));
test('19b plan-mode account details stay in the plan workflow',()=>assert.equal(intents.deterministic('use my live account on gold at one percent risk',{planMode:true}).intent,'ADD_PLAN_DETAILS'));
test('19c resettable entry timer compiles as a durable behavior intent',()=>{const parsed=intents.deterministic('Every new entry reset my timer for 5 minutes, then protect profit');assert.equal(parsed.type,'BEHAVIOR');assert.equal(parsed.intent,'RESETTABLE_ENTRY_TIMER');assert.equal(parsed.parameters.timeoutSeconds,300);assert.equal(parsed.parameters.onTimeout,'PROTECT_PROFIT_FULL_BASKET');});
test('20 plan extraction risk',()=>assert.equal(intents.extractPlanFields('Use one-percent risk').risk.value,1));
test('21 plan extraction drawdown',()=>assert.equal(intents.extractPlanFields('stop at 10 percent drawdown').limits.maxDrawdownPercent,10));
test('22 plan extraction daily target',()=>assert.equal(intents.extractPlanFields('when I make $500').targets.dailyProfitUsd,500));
test('23 plan extraction runner',()=>assert.equal(intents.extractPlanFields('leave one runner').runnerCount,1));
test('24 plan extraction trailing rule',()=>assert.ok(intents.extractPlanFields('trail the runner at 20 percent').targetActions.includes('TRAIL_RUNNER_20_PERCENT')));
test('25 default plan validates',()=>assert.equal(validateDailyPlan(defaultDailyPlan('u')).ok,true));
test('26 invalid plan risk is rejected',()=>assert.equal(validateDailyPlan(defaultDailyPlan('u',{risk:{mode:'PERCENT',value:101}})).ok,false));
test('27 plan read-back includes account and target',()=>assert.match(planService.readBack(defaultDailyPlan('u',{accountIds:['4721'],targets:{dailyProfitUsd:500},risk:{mode:'PERCENT',value:1}})),/4721.*1-percent risk.*\$500/));
test('28 plan compiler creates drawdown condition',()=>assert.ok(planService.compileRules(defaultDailyPlan('u',{limits:{maxDrawdownPercent:10}})).some((r)=>r.type==='MAX_DRAWDOWN_PERCENT')));
test('29 runner rule is marked unsupported',()=>assert.equal(planService.compileRules(defaultDailyPlan('u',{targetActions:['LEAVE_BEST_RUNNER']}))[0].supported,false));
test('30 read-only safety needs no confirmation',()=>assert.equal(safety.requiresConfirmation(safety.classify({type:'QUERY',intent:'ACCOUNT_STATUS'})),false));
test('31 controlled safety needs confirmation',()=>assert.equal(safety.classify({type:'ACTION',intent:'PAUSE_COPIER'}),'CONTROLLED'));
test('32 dangerous close safety is strong',()=>assert.equal(safety.requiresStrongConfirmation(safety.classify({type:'ACTION',intent:'CLOSE_ALL_TRADES'})),true));
test('32b command name cannot disguise a dangerous action',()=>assert.equal(safety.classify({type:'ACTION',intent:'GENERAL_ACTION',commandName:'CLOSE_ALL_LOSERS'}),'DANGEROUS'));
test('33 unauthorized account is rejected',()=>assert.throws(()=>safety.assertAccountAccess(['2'],[{accountId:'1'}]),/not authorized/));
test('34 authorized account is accepted',()=>assert.equal(safety.assertAccountAccess(['1'],[{accountId:'1'}]),true));
test('34b view-only shared account cannot execute',()=>assert.throws(()=>safety.assertAccountAccess(['1'],[{accountId:'1',shared:true,sharePermission:'view_only'}]),/not authorized/));
test('35 confirmation binding is stable by key order',()=>assert.equal(confirmationActionHash({a:1,b:2}),confirmationActionHash({b:2,a:1})));
test('36 confirmation binding changes with parameters',()=>assert.notEqual(confirmationActionHash({risk:1}),confirmationActionHash({risk:2})));
test('37 queued response does not claim completion',()=>assert.doesNotMatch(new WisdoExecutionService().responseFor({status:'pending',command:'STOP_ENTRIES'}),/Completed/));
test('38 completed response requires completed status',()=>assert.match(new WisdoExecutionService().responseFor({status:'completed',result:{message:'MT4 applied it.'}}),/^Completed/));
test('39 partial completion is not fabricated by response service',()=>assert.match(new WisdoExecutionService().responseFor({status:'failed',result:{message:'2 trades remain'}}),/failed/i));
test('39b basket verification requires evidence for every target ticket',()=>{const execution=new WisdoExecutionService();const command={status:'completed',payload:{targetTickets:['1','2']}};assert.equal(execution.verification(command,[{lifecycle_status:'COMPLETED',result:{closedTickets:['1'],remainingTickets:['2']}}]).verified,false);assert.equal(execution.verification(command,[{lifecycle_status:'COMPLETED',result:{closedTickets:['1','2'],remainingTickets:[]}}]).verified,true);});
test('40 drawdown target condition',()=>assert.equal(new WisdoPlanMonitorService().condition({rule_type:'MAX_DRAWDOWN_PERCENT',parameters:{threshold:10}},{drawdownPercent:11}),true));
test('41 profit target condition',()=>assert.equal(new WisdoPlanMonitorService().condition({rule_type:'DAILY_PROFIT_USD',parameters:{threshold:500}},{dailyProfit:500}),true));
test('42 loss target condition',()=>assert.equal(new WisdoPlanMonitorService().condition({rule_type:'MAX_DAILY_LOSS_USD',parameters:{threshold:200}},{dailyLoss:199}),false));
test('42b expired resettable timer queues one verified full-basket close only when profitable',async()=>{let queued=null;const pool={query:async(sql)=>{if(sql.startsWith('SELECT * FROM wisdo_behavior_runtime_state'))return{rows:[{state:'ARMED',open_tickets:['1'],deadline_at:'2026-01-01T00:00:00.000Z'}]};if(sql.startsWith('UPDATE wisdo_behavior_runtime_state SET state'))return{rowCount:1,rows:[{}]};return{rowCount:1,rows:[]};}};const monitor=new WisdoPlanMonitorService({pool,executionService:{queue:async(input)=>{queued=input;return{id:'cmd-1'};}}});const events=await monitor.evaluateResettableTimer({behavior_id:'b1',owner_user_id:'u',definition:{trigger:{timeout_seconds:60}},source_text:'protect it'},'a1',{openTrades:[{ticket:'1',profit:25}]},new Date('2026-01-01T00:02:00.000Z'));assert.equal(queued.commandName,'CLOSE_ALL_TRADES');assert.equal(queued.parameters.atomic,true);assert.deepEqual(queued.parameters.targetTickets,['1']);assert.equal(events[0].event,'full_basket_close_queued');});
test('42c resettable timer never closes a flat or losing basket',async()=>{let queued=false;const pool={query:async(sql)=>sql.startsWith('SELECT * FROM wisdo_behavior_runtime_state')?{rows:[{state:'ARMED',open_tickets:['1'],deadline_at:'2026-01-01T00:00:00.000Z'}]}:{rowCount:1,rows:[]}};const monitor=new WisdoPlanMonitorService({pool,executionService:{queue:async()=>{queued=true;}}});const events=await monitor.evaluateResettableTimer({behavior_id:'b1',owner_user_id:'u',definition:{trigger:{timeout_seconds:60}}},'a1',{openTrades:[{ticket:'1',profit:-1}]},new Date('2026-01-01T00:02:00.000Z'));assert.equal(queued,false);assert.equal(events[0].reason,'basket_not_profitable');});
test('42d generalized behavior targets only tickets inside exact symbol scope',async()=>{let queued=null;const pool={query:async(sql)=>{if(sql.startsWith('SELECT * FROM wisdo_behavior_runtime_state'))return{rows:[{state:'ARMED',open_tickets:[],metadata:{}}]};if(sql.startsWith('UPDATE wisdo_behavior_runtime_state SET state'))return{rowCount:1,rows:[{}]};return{rowCount:1,rows:[]};}};const monitor=new WisdoPlanMonitorService({pool,executionService:{queue:async(input)=>{queued=input;return{id:'cmd-scope'};}}});const definition={trigger:{type:'event',event:'new_entry'},conditions:[],unless:[],actions:[{type:'close_full_basket',parameters:{atomic:true}}],failure_plan:{max_attempts:3}};await monitor.evaluateGeneralBehavior({behavior_id:'b-scope',owner_user_id:'u',status:'active',scope:{symbol:'XAUUSD'},definition},'a1',{openTrades:[{ticket:'gold',symbol:'XAUUSD',profit:2},{ticket:'euro',symbol:'EURUSD',profit:3}]},new Date('2026-01-01T00:00:00.000Z'));assert.deepEqual(queued.parameters.targetTickets,['gold']);assert.equal(queued.parameters.symbol,'XAUUSD');});
test('42e first snapshot establishes an event baseline instead of treating old tickets as new',async()=>{let queued=false;const pool={query:async(sql)=>sql.startsWith('SELECT * FROM wisdo_behavior_runtime_state')?{rows:[]}:{rowCount:1,rows:[]}};const monitor=new WisdoPlanMonitorService({pool,executionService:{queue:async()=>{queued=true;}}});const definition={trigger:{type:'event',event:'new_entry'},conditions:[],unless:[],actions:[{type:'pause_entries'}]};await monitor.evaluateGeneralBehavior({behavior_id:'baseline',owner_user_id:'u',status:'active',scope:{},definition},'a1',{openTrades:[{ticket:'existing'}]},new Date());assert.equal(queued,false);});
test('43 physical mute blocks conversation',()=>assert.throws(()=>new WisdoDeviceService().assertPermission({muted:true,permissions:{}},'conversation'),/muted/));
test('44 device permission is enforced',()=>assert.throws(()=>new WisdoDeviceService().assertPermission({muted:false,permissions:{conversation:false}},'conversation'),/not permitted/));
test('45 relational schema contains required tables',()=>{for(const table of ['wisdo_voice_devices','wisdo_conversation_sessions','wisdo_conversation_messages','wisdo_daily_plans','wisdo_plan_rules','wisdo_plan_targets','wisdo_plan_execution_events','wisdo_pending_confirmations','wisdo_command_receipts','wisdo_conditional_rule_state','wisdo_education_progress','wisdo_notification_deduplication'])assert.match(migration,new RegExp(table));});
test('46 API contract contains device, session, plan and receipt routes',()=>{for(const path of ['/devices/register','/devices/heartbeat','/sessions','/conversation','/plans','/confirmations/pending','/commands/:commandId','/education/progress'])assert.match(routes,new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('47 existing command deduplication remains',()=>assert.match(mt4,/dedupeKey/));
test('47b conversational execution supplies the command bus dedupe key',async()=>{let payload;const execution=new WisdoExecutionService({pool:{query:async()=>({rows:[{}]})},mt4CommandService:{queueCommandForAccount:async(_u,_a,_c,p)=>{payload=p;return{id:'cmd',createdAt:new Date().toISOString()};}}});await execution.queue({userId:'u',accountId:'a',intent:'STOP_NEW_ENTRIES',commandName:'STOP_ENTRIES',rawText:'pause trading'});assert.equal(payload.dedupeKey,payload.idempotencyKey);});
test('48 existing Reporter lifecycle remains',()=>{assert.match(mt4,/markCommandDelivered/);assert.match(mt4,/markCommandCompleted/);assert.match(mt4,/markCommandFailed/);});
test('49 database-first command pressure indexes remain in migration',()=>assert.match(migration,/idx_wisdo_receipts_command/));
test('50 conversation service always catches processing failures',()=>assert.match(WisdoConversationService.prototype.answer.toString(),/COACH_RESPONSES\.failed/));
test('51 general conversation survives intent-provider failure',async()=>{const provider={extractIntent:async()=>{throw new Error('provider unavailable');}};const result=await new WisdoIntentService({provider}).parse('what is todays date',{});assert.equal(result.intent,'GENERAL_CONVERSATION');});
test('52 date questions have a deterministic answer path',()=>assert.match(WisdoConversationService.prototype.handle.toString(),/Today is/));
