import { SlashCommandBuilder } from 'discord.js';
import { AccountSelectionService } from '../services/accountSelectionService.js';
import { commandStatusLabel } from '../services/commandEnvelopeService.js';
import { simulateCopierEvent } from '../services/copierSafetyService.js';

function money(value){return Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD'});}
function accountLine(account){return `**${account.nickname||account.accountId}** · ${account.accountType} · ${account.health}\nBroker: ${account.brokerName||'unknown'} / ${account.brokerServer||'unknown'} · Login: ****${String(account.mt4Login||'').slice(-4)}\nBalance ${money(account.balance)} · Equity ${money(account.equity)} · Floating ${money(account.floatingProfit)} · Daily ${money(account.dailyProfit)}`;}
function option(builder){return builder.addStringOption((o)=>o.setName('account').setDescription('Exact nickname, account ID, or Account 2').setRequired(false));}

export function buildOperationsCommands(context={}){
  const accounts=context.accountSelectionService||new AccountSelectionService({repository:context.mt4SyncService?.repository,memoryService:context.wisdoMemoryService});
  const read=async(interaction)=>accounts.resolve(interaction.user.id,interaction.options?.getString?.('account'),{permission:'view'});
  const control=async(interaction)=>accounts.resolve(interaction.user.id,interaction.options?.getString?.('account'),{permission:'control'});
  const commands=[];
  const simple=(name,description,execute)=>commands.push({data:option(new SlashCommandBuilder().setName(name).setDescription(description)),async execute(interaction){await interaction.deferReply({ephemeral:true});await execute(interaction,await read(interaction));}});
  commands.push({data:new SlashCommandBuilder().setName('help').setDescription('Show the canonical WISDO operating commands.'),async execute(interaction){await interaction.reply({ephemeral:true,content:'Use `/my-accounts`, `/switch-account`, `/account-health`, `/open-trades`, `/command-queue`, `/copier-status`, `/bot-lanes`, and `/system-status`. Trading controls always show the selected account and queue state.'});}});
  simple('system-status','Show WISDO and selected-account health.',async(i,a)=>i.editReply(`WISDO operating core: **online**\n${accountLine(a)}`));
  simple('command-health','Show command transport health for the selected account.',async(i,a)=>{const health=context.mt4CommandService?.health?await context.mt4CommandService.health().catch(()=>null):null;await i.editReply(`${accountLine(a)}\nCommand transport: **${health?.ok===false?'degraded':'ready'}**`);});
  simple('active-account','Show the explicitly saved active trading account.',async(i,a)=>i.editReply(accountLine(a)));
  commands.push({data:new SlashCommandBuilder().setName('switch-account').setDescription('Save an exact active account for later commands.').addStringOption((o)=>o.setName('account').setDescription('Nickname, ID, or Account 2').setRequired(true)),async execute(interaction){await interaction.deferReply({ephemeral:true});const candidate=await accounts.resolve(interaction.user.id,interaction.options.getString('account'),{allowActive:false});const selected=await accounts.select(interaction.user.id,candidate.accountId);await interaction.editReply(`Active account saved.\n${accountLine(selected)}`);}});
  simple('account-health','Show Reporter-derived account health.',async(i,a)=>i.editReply(accountLine(a)));
  simple('account-details','Show exact account identity and metrics.',async(i,a)=>i.editReply(`${accountLine(a)}\nAccount ID: \`${a.accountId}\`\nReporter: ${a.reporterVersion||'unknown'} · Last sync: ${a.lastSyncAt||'never'}`));
  simple('open-trades','Show stored open positions for the selected account.',async(i,a)=>{const rows=a.latestSnapshot?.snapshot?.positions||a.latestSnapshot?.snapshot?.openTrades||[];await i.editReply(`${accountLine(a)}\n${rows.length?rows.slice(0,20).map((p)=>`\`${p.ticket||'?'}\` ${p.symbol||'?'} ${p.type||p.side||''} ${p.lots||p.volume||''}`).join('\n'):'No open positions in the latest Reporter snapshot.'}`);});
  simple('trade-history','Show recent stored trade history for the selected account.',async(i,a)=>{const rows=await context.mt4SyncService?.repository?.getMt4SnapshotHistory?.(i.user.id,10,{accountId:a.legacyAccountId||a.accountId})||[];await i.editReply(`${accountLine(a)}\nStored snapshot records: **${rows.length}**`);});
  simple('copier-status','Show copier role and state for the selected account.',async(i,a)=>i.editReply(`${accountLine(a)}\nCopier role: **${a.accountRole||'private'}** · Permission: **${a.copyPermission||'private'}** · ${a.copyRisk?.copierPaused?'paused':'ready'}`));
  simple('copier-routes','Show copier routes involving the selected account.',async(i,a)=>{const routes=await context.mt4SyncService?.repository?.getCopyRoutesForUser?.(i.user.id)||[];const filtered=routes.filter((r)=>[r.leaderAccountId,r.masterAccountId,r.followerAccountId].map(String).includes(String(a.legacyAccountId||a.accountId)));await i.editReply(filtered.length?filtered.slice(0,20).map((r)=>`\`${r.routeId||r.copyRouteId||'route'}\` ${r.leaderAccountId||r.masterAccountId} → ${r.followerAccountId} · ${r.status||'active'}`).join('\n'):'No copier routes for this account.');});
  commands.push({data:new SlashCommandBuilder().setName('copier-test').setDescription('Dry-run one copier event without queueing MT4 work.').addStringOption((o)=>o.setName('symbol').setDescription('Source symbol').setRequired(true)).addNumberOption((o)=>o.setName('lots').setDescription('Source lot size').setRequired(true)).addStringOption((o)=>o.setName('account').setDescription('Follower account').setRequired(false)),async execute(interaction){await interaction.deferReply({ephemeral:true});const a=await read(interaction);const result=simulateCopierEvent({event:{sourceEventId:`discord:${interaction.id}`,symbol:interaction.options.getString('symbol'),lots:interaction.options.getNumber('lots'),action:'OPEN_MARKET'},route:{masterAccountId:'diagnostic-master',followerAccountId:a.accountId,lotPolicy:{mode:'fixed',fixedLot:0.01},riskPolicy:{maxOpenPositions:100}},followerSnapshot:{symbols:a.latestSnapshot?.snapshot?.symbols||[],balance:a.balance,equity:a.equity,openTradeCount:a.openTrades||0}});await interaction.editReply(`Dry run only — nothing queued.\n\`\`\`json\n${JSON.stringify(result,null,2).slice(0,1700)}\n\`\`\``);}});
  simple('reporter-status','Show Reporter connectivity and version.',async(i,a)=>i.editReply(`${accountLine(a)}\nReporter ${a.reporterVersion||'unknown'} · terminal ${a.terminalId||'unknown'} · last heartbeat ${a.lastHeartbeatAt||a.lastSyncAt||'never'}`));
  simple('connection-doctor','Diagnose account and Reporter connectivity.',async(i,a)=>{const issues=[];if(a.health!=='CONNECTED')issues.push(`health=${a.health}`);if(!a.lastSyncAt)issues.push('no snapshot received');if(a.accountType==='UNKNOWN')issues.push('account type unproven');await i.editReply(`${accountLine(a)}\n${issues.length?`Issues: ${issues.join(', ')}`:'No connection defect detected in stored state.'}`);});
  simple('command-queue','Show recent command lifecycle state.',async(i,a)=>{const state=await context.mt4CommandService?.load?.()||{};const rows=(state.commandQueue||[]).filter((row)=>String(row.accountId||row.payload?.accountId||'')===String(a.legacyAccountId||a.accountId)).slice(0,15);await i.editReply(rows.length?rows.map((row)=>`\`${row.id}\` ${row.command} · **${commandStatusLabel(String(row.status||'PENDING').toUpperCase().replace('LEASED','DELIVERED'))}**`).join('\n'):'No queued commands for this account.');});
  simple('bot-lanes','Show Reporter-discovered bot lanes.',async(i,a)=>{const rows=a.latestSnapshot?.snapshot?.bots||a.latestSnapshot?.snapshot?.lanes||[];await i.editReply(rows.length?rows.map((b)=>`**${b.name||b.eaName||b.botId||'Bot'}** · ${b.symbol||'multi'} · magic ${b.magicNumber??'?'} · ${b.status||'unknown'}`).join('\n'):'No bot lanes reported for this account.');});
  const actions=[['pause-bot','Pause one exact bot lane.','PAUSE_BOT'],['resume-bot','Resume one exact bot lane.','RESUME_BOT'],['close-profitable','Close profitable positions after confirmation.','CLOSE_ALL_WINNERS'],['close-losing','Close losing positions after confirmation.','CLOSE_ALL_LOSERS'],['close-all','Close all positions after confirmation.','CLOSE_ALL'],['emergency-stop','Emergency-stop the selected account after confirmation.','EMERGENCY_STOP']];
  for(const [name,description,action] of actions){let builder=new SlashCommandBuilder().setName(name).setDescription(description);if(name.includes('bot'))builder=builder.addStringOption((o)=>o.setName('lane').setDescription('Exact lane ID').setRequired(true));builder=builder.addBooleanOption((o)=>o.setName('confirm').setDescription('Confirm this trading action').setRequired(true)).addStringOption((o)=>o.setName('account').setDescription('Exact nickname, account ID, or Account 2').setRequired(false));commands.push({data:builder,async execute(interaction){await interaction.deferReply({ephemeral:true});if(!interaction.options.getBoolean('confirm'))return interaction.editReply('No command queued. Strong confirmation was not supplied.');const a=await control(interaction);const laneId=interaction.options.getString('lane');const command=await context.mt4CommandService.queueCommandForAccount(interaction.user.id,a.legacyAccountId||a.accountId,action,{accountId:a.legacyAccountId||a.accountId,laneId,source:'discord',safetyLevel:name==='emergency-stop'?'EMERGENCY':'HIGH_RISK',confirmation:'confirmed'});await interaction.editReply(`${accountLine(a)}\nAction: **${action}**${laneId?` · lane **${laneId}**`:''}\nStatus: **Queued** — not yet executed.\nCommand: \`${command.id}\``);}});}
  commands.push({data:new SlashCommandBuilder().setName('report-problem').setDescription('Create an operational problem reference.').addStringOption((o)=>o.setName('description').setDescription('What failed?').setRequired(true)),async execute(interaction){const description=interaction.options.getString('description').slice(0,800);context.logger?.warn?.('User reported an operational problem',{problemReference:interaction.id,userId:interaction.user.id,guildId:interaction.guildId||null,description});await interaction.reply({ephemeral:true,content:`Problem reference \`${interaction.id}\` logged for operator review. No trading action was taken.\n${description}`});}});
  return {commands,modalHandlers:new Map()};
}
