import { WisdoBehaviorCompilerService } from './wisdoBehaviorCompilerService.js';
const ACTION_COMMANDS=Object.freeze({STOP_NEW_ENTRIES:'STOP_ENTRIES',PAUSE_COPIER:'PAUSE_COPIER',CLOSE_PROFITABLE_TRADES:'CLOSE_ALL_WINNERS'});

function metrics(s={}) { const balance=Number(s.balance||0),equity=Number(s.equity||balance),daily=Number(s.dailyClosedPL||0);return {balance,equity,dailyProfit:daily,dailyLoss:Math.max(0,-daily),drawdownPercent:balance>0?Math.max(0,(balance-equity)/balance*100):0}; }
function openTrades(snapshot={},scope={}) { return (Array.isArray(snapshot.openTrades)?snapshot.openTrades:[]).filter((trade)=>{if(scope.symbol&&String(trade.symbol||'').toUpperCase()!==String(scope.symbol).toUpperCase())return false;if(scope.magic_number!=null&&String(trade.magicNumber??trade.magic_number??'')!==String(scope.magic_number))return false;if(scope.campaign_id&&![trade.campaignId,trade.campaign_id,trade.comment].some((value)=>String(value||'').toLowerCase().includes(String(scope.campaign_id).toLowerCase())))return false;return true;}); }
function ticketSet(trades=[]) { return [...new Set(trades.map((trade)=>String(trade.ticket||'')).filter(Boolean))].sort(); }
function basketProfit(trades=[]) { return trades.reduce((sum,trade)=>sum+Number(trade.profit||0)+Number(trade.swap||0)+Number(trade.commission||0),0); }

export class WisdoPlanMonitorService {
  constructor({pool,executionService,planService=null,notificationService=null,behaviorCompiler=null,logger=console}={}) { Object.assign(this,{pool,executionService,planService,notificationService,logger});this.behaviorCompiler=behaviorCompiler||new WisdoBehaviorCompilerService();this.lastResetCheck=0; }
  condition(rule,m) { const p=rule.parameters||{};if(rule.rule_type==='MAX_DRAWDOWN_PERCENT')return m.drawdownPercent>=Number(p.threshold);if(rule.rule_type==='MAX_DAILY_LOSS_USD')return m.dailyLoss>=Number(p.threshold);if(rule.rule_type==='DAILY_PROFIT_USD')return m.dailyProfit>=Number(p.threshold);return false; }

  async ingestSnapshot({connectionRecord={},latestSnapshotRecord={}}={}) {
    const accountId=String(connectionRecord.accountId||latestSnapshotRecord.accountId||'');if(!accountId)return[];
    if(this.planService&&Date.now()-this.lastResetCheck>60000){this.lastResetCheck=Date.now();await this.planService.automaticResets().catch((error)=>this.logger.warn?.('Daily Plan reset check failed',{message:error.message}));}
    const snapshot=latestSnapshotRecord.snapshot||{};
    return [...await this.ingestPlanRules(accountId,snapshot),...await this.ingestBehaviors(accountId,snapshot)];
  }

  async ingestPlanRules(accountId,snapshot) {
    const m=metrics(snapshot);const r=await this.pool.query(`SELECT r.*,p.account_ids FROM wisdo_plan_rules r JOIN wisdo_daily_plans p ON p.plan_id=r.plan_id WHERE p.status='ACTIVE' AND r.status='ARMED' AND r.supported=TRUE AND $1=ANY(p.account_ids)`,[accountId]);const events=[];
    for(const rule of r.rows){if(!this.condition(rule,m)){await this.pool.query(`INSERT INTO wisdo_conditional_rule_state(rule_id,owner_user_id,account_id,state,last_value,last_checked_at) VALUES($1,$2,$3,'ARMED',$4,NOW()) ON CONFLICT(rule_id) DO UPDATE SET last_value=EXCLUDED.last_value,last_checked_at=NOW(),updated_at=NOW()`,[rule.rule_id,rule.owner_user_id,accountId,m.drawdownPercent]);continue;}const claimed=await this.pool.query(`UPDATE wisdo_plan_rules SET status='TRIGGERED',updated_at=NOW() WHERE rule_id=$1 AND status='ARMED' RETURNING *`,[rule.rule_id]);if(!claimed.rowCount)continue;const actions=rule.parameters?.actions||[];for(const action of actions){if(!ACTION_COMMANDS[action])continue;try{const command=await this.executionService.queue({userId:rule.owner_user_id,accountId,intent:action,commandName:ACTION_COMMANDS[action],parameters:{planRuleId:rule.rule_id},rawText:`Daily Plan rule ${rule.rule_type}`,safetyLevel:'CONTROLLED',planId:rule.plan_id,confirmationStatus:'CONFIRMED'});events.push({ruleId:rule.rule_id,action,commandId:command.id});}catch(error){events.push({ruleId:rule.rule_id,action,error:error.message});}}await this.pool.query(`INSERT INTO wisdo_plan_execution_events(event_id,plan_id,rule_id,owner_user_id,event_type,detail) VALUES(gen_random_uuid(),$1,$2,$3,'RULE_TRIGGERED',$4::jsonb)`,[rule.plan_id,rule.rule_id,rule.owner_user_id,JSON.stringify({metrics:m,events})]);}return events;
  }

  async ingestBehaviors(accountId,snapshot,now=new Date()) {
    const result=await this.pool.query(`SELECT * FROM wisdo_behaviors WHERE status IN ('active','shadow') AND scope->>'account_id'=$1 AND (expires_at IS NULL OR expires_at>NOW())`,[accountId]);const events=[];
    for(const row of result.rows){if(row.definition?.trigger?.type==='resettable_inactivity_timer')events.push(...await this.evaluateResettableTimer(row,accountId,snapshot,now));else events.push(...await this.evaluateGeneralBehavior(row,accountId,snapshot,now));}return events;
  }

  async evaluateResettableTimer(row,accountId,snapshot,now=new Date()) {
    const definition=row.definition||{},timeoutSeconds=Math.max(1,Number(definition.trigger?.timeout_seconds||0));if(!Number.isFinite(timeoutSeconds)||timeoutSeconds<=0)return[];
    const trades=openTrades(snapshot,row.scope),tickets=ticketSet(trades),profit=basketProfit(trades);const priorResult=await this.pool.query(`SELECT * FROM wisdo_behavior_runtime_state WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId]);const prior=priorResult.rows[0];const priorTickets=Array.isArray(prior?.open_tickets)?prior.open_tickets.map(String):[];const newTickets=tickets.filter((ticket)=>!priorTickets.includes(ticket));const reset=Boolean(newTickets.length)||!prior;const deadline=reset?new Date(now.getTime()+timeoutSeconds*1000):new Date(prior.deadline_at);const metadata={newTickets,basketProfit:profit,openCount:tickets.length};
    if(reset||now<deadline||prior?.state==='FIRED'){await this.pool.query(`INSERT INTO wisdo_behavior_runtime_state(behavior_id,owner_user_id,account_id,state,open_tickets,last_entry_at,deadline_at,last_checked_at,metadata) VALUES($1,$2,$3,'ARMED',$4::jsonb,$5,$6,$5,$7::jsonb) ON CONFLICT(behavior_id,account_id) DO UPDATE SET state=CASE WHEN wisdo_behavior_runtime_state.state='FIRED' THEN 'FIRED' ELSE 'ARMED' END,open_tickets=EXCLUDED.open_tickets,last_entry_at=CASE WHEN $8 THEN EXCLUDED.last_entry_at ELSE wisdo_behavior_runtime_state.last_entry_at END,deadline_at=CASE WHEN $8 THEN EXCLUDED.deadline_at ELSE wisdo_behavior_runtime_state.deadline_at END,last_checked_at=EXCLUDED.last_checked_at,metadata=EXCLUDED.metadata,updated_at=NOW()`,[row.behavior_id,row.owner_user_id,accountId,JSON.stringify(tickets),now,deadline,JSON.stringify(metadata),reset]);return reset&&newTickets.length?[{behaviorId:row.behavior_id,event:'timer_reset',newTickets,deadlineAt:deadline.toISOString()}]:[];}
    if(!tickets.length||profit<=0){await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET open_tickets=$3::jsonb,last_checked_at=$4,metadata=$5::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId,JSON.stringify(tickets),now,JSON.stringify({...metadata,blockedReason:!tickets.length?'no_open_trades':'basket_not_profitable'})]);return [{behaviorId:row.behavior_id,event:'timeout_blocked',reason:!tickets.length?'no_open_trades':'basket_not_profitable'}];}
    if(row.status==='shadow'){await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='ARMED',last_checked_at=$3,metadata=$4::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId,now,JSON.stringify({...metadata,shadowWouldFire:true,targetTickets:tickets})]);return [{behaviorId:row.behavior_id,event:'shadow_would_close_full_basket',targetTickets:tickets,basketProfit:profit}];}
    const claimed=await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='FIRED',last_checked_at=$3,last_triggered_at=$3,metadata=$4::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2 AND state='ARMED' RETURNING *`,[row.behavior_id,accountId,now,JSON.stringify({...metadata,targetTickets:tickets})]);if(!claimed.rowCount)return[];
    try{const command=await this.executionService.queue({userId:row.owner_user_id,accountId,intent:'PROTECT_PROFIT_FULL_BASKET',commandName:'CLOSE_ALL_TRADES',parameters:{behaviorId:row.behavior_id,targetTickets:tickets,atomic:true,requirePositiveBasket:true,symbol:row.scope?.symbol||undefined,magicNumber:row.scope?.magic_number??undefined,campaignId:row.scope?.campaign_id||undefined,idempotencyKey:`behavior:${row.behavior_id}:${deadline.toISOString()}`},rawText:row.source_text||'Resettable entry protection timer',safetyLevel:'DANGEROUS',confirmationStatus:'CONFIRMED'});return [{behaviorId:row.behavior_id,event:'full_basket_close_queued',commandId:command.id,targetTickets:tickets,basketProfit:profit}];}
    catch(error){await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='FAILED',metadata=metadata||$3::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId,JSON.stringify({failure:error.message,targetTickets:tickets})]);return [{behaviorId:row.behavior_id,event:'execution_failed',error:error.message}];}
  }

  async evaluateGeneralBehavior(row,accountId,snapshot,now=new Date()) {
    const trades=openTrades(snapshot,row.scope),tickets=ticketSet(trades),scopedSnapshot={...snapshot,openTrades:trades},priorResult=await this.pool.query(`SELECT * FROM wisdo_behavior_runtime_state WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId]),prior=priorResult.rows[0];const priorTickets=Array.isArray(prior?.open_tickets)?prior.open_tickets.map(String):[];const newTickets=prior?tickets.filter((ticket)=>!priorTickets.includes(ticket)):[];const trigger=row.definition?.trigger||{};const intervalDue=trigger.type==='interval'&&Boolean(prior?.deadline_at)&&now>=new Date(prior.deadline_at);const evaluation=this.behaviorCompiler.evaluate(row,scopedSnapshot,{type:newTickets.length?'new_entry':null,interval_due:intervalDue});const nextDeadline=trigger.type==='interval'?new Date(now.getTime()+Number(trigger.interval_seconds||60)*1000):prior?.deadline_at||null;const attempts=Number(prior?.metadata?.attempts||0),metadata={evaluation,newTickets,openCount:tickets.length,attempts};
    if(evaluation.terminated){await this.pool.query(`UPDATE wisdo_behaviors SET status='cancelled',updated_at=NOW() WHERE behavior_id=$1 AND owner_user_id=$2`,[row.behavior_id,row.owner_user_id]);return[{behaviorId:row.behavior_id,event:'behavior_terminated',explanation:evaluation.explanation}];}
    if(row.status==='shadow'||!evaluation.wouldFire){await this.pool.query(`INSERT INTO wisdo_behavior_runtime_state(behavior_id,owner_user_id,account_id,state,open_tickets,deadline_at,last_checked_at,metadata) VALUES($1,$2,$3,'ARMED',$4::jsonb,$5,$6,$7::jsonb) ON CONFLICT(behavior_id,account_id) DO UPDATE SET state='ARMED',open_tickets=EXCLUDED.open_tickets,deadline_at=COALESCE(EXCLUDED.deadline_at,wisdo_behavior_runtime_state.deadline_at),last_checked_at=EXCLUDED.last_checked_at,metadata=EXCLUDED.metadata,updated_at=NOW()`,[row.behavior_id,row.owner_user_id,accountId,JSON.stringify(tickets),nextDeadline,now,JSON.stringify(metadata)]);return row.status==='shadow'&&evaluation.wouldFire?[{behaviorId:row.behavior_id,event:'shadow_would_execute',evaluation}]:[];}
    if(prior?.state==='FIRED'&&trigger.type!=='interval'&&trigger.type!=='event')return[];
    const claimed=prior?await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='FIRED',open_tickets=$3::jsonb,deadline_at=$4,last_checked_at=$5,last_triggered_at=$5,metadata=$6::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2 AND state<>'FIRED' RETURNING *`,[row.behavior_id,accountId,JSON.stringify(tickets),nextDeadline,now,JSON.stringify(metadata)]):await this.pool.query(`INSERT INTO wisdo_behavior_runtime_state(behavior_id,owner_user_id,account_id,state,open_tickets,deadline_at,last_checked_at,last_triggered_at,metadata) VALUES($1,$2,$3,'FIRED',$4::jsonb,$5,$6,$6,$7::jsonb) ON CONFLICT DO NOTHING RETURNING *`,[row.behavior_id,row.owner_user_id,accountId,JSON.stringify(tickets),nextDeadline,now,JSON.stringify(metadata)]);if(!claimed.rowCount)return[];
    const maxAttempts=Math.max(1,Number(row.definition?.failure_plan?.max_attempts||3));if(attempts>=maxAttempts){await this.pool.query(`UPDATE wisdo_behaviors SET status='paused',updated_at=NOW() WHERE behavior_id=$1 AND owner_user_id=$2`,[row.behavior_id,row.owner_user_id]);return[{behaviorId:row.behavior_id,event:'retry_exhausted',attempts}];}
    const events=[];for(const action of row.definition?.actions||[]){const command=this.behaviorCompiler.commandFor(action);if(!command){events.push({behaviorId:row.behavior_id,event:'notification_due',action:action.type});continue;}try{const queued=await this.executionService.queue({userId:row.owner_user_id,accountId,intent:command.intent,commandName:command.commandName,parameters:{...command.parameters,behaviorId:row.behavior_id,scope:row.scope,targetTickets:tickets,symbol:row.scope?.symbol||undefined,magicNumber:row.scope?.magic_number??undefined,campaignId:row.scope?.campaign_id||undefined,idempotencyKey:`behavior:${row.behavior_id}:${now.toISOString()}`},rawText:row.source_text||row.purpose||'Compiled WISDO behavior',safetyLevel:command.safetyLevel,confirmationStatus:'CONFIRMED'});events.push({behaviorId:row.behavior_id,event:'behavior_command_queued',commandId:queued.id,action:action.type});}catch(error){const nextAttempts=attempts+1;await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='FAILED',metadata=metadata||$3::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId,JSON.stringify({failure:error.message,action:action.type,attempts:nextAttempts})]);if(nextAttempts>=maxAttempts)await this.pool.query(`UPDATE wisdo_behaviors SET status='paused',updated_at=NOW() WHERE behavior_id=$1 AND owner_user_id=$2`,[row.behavior_id,row.owner_user_id]);events.push({behaviorId:row.behavior_id,event:nextAttempts>=maxAttempts?'retry_exhausted':'execution_failed',error:error.message,attempts:nextAttempts});}}
    return events;
  }
}
