const ACTION_COMMANDS=Object.freeze({STOP_NEW_ENTRIES:'STOP_ENTRIES',PAUSE_COPIER:'PAUSE_COPIER',CLOSE_PROFITABLE_TRADES:'CLOSE_ALL_WINNERS'});

function metrics(s={}) { const balance=Number(s.balance||0),equity=Number(s.equity||balance),daily=Number(s.dailyClosedPL||0);return {balance,equity,dailyProfit:daily,dailyLoss:Math.max(0,-daily),drawdownPercent:balance>0?Math.max(0,(balance-equity)/balance*100):0}; }
function openTrades(snapshot={}) { return Array.isArray(snapshot.openTrades)?snapshot.openTrades:[]; }
function ticketSet(trades=[]) { return [...new Set(trades.map((trade)=>String(trade.ticket||'')).filter(Boolean))].sort(); }
function basketProfit(trades=[]) { return trades.reduce((sum,trade)=>sum+Number(trade.profit||0)+Number(trade.swap||0)+Number(trade.commission||0),0); }

export class WisdoPlanMonitorService {
  constructor({pool,executionService,planService=null,notificationService=null,logger=console}={}) { Object.assign(this,{pool,executionService,planService,notificationService,logger});this.lastResetCheck=0; }
  condition(rule,m) { const p=rule.parameters||{};if(rule.rule_type==='MAX_DRAWDOWN_PERCENT')return m.drawdownPercent>=Number(p.threshold);if(rule.rule_type==='MAX_DAILY_LOSS_USD')return m.dailyLoss>=Number(p.threshold);if(rule.rule_type==='DAILY_PROFIT_USD')return m.dailyProfit>=Number(p.threshold);return false; }

  async ingestSnapshot({connectionRecord={},latestSnapshotRecord={}}={}) {
    const accountId=String(connectionRecord.accountId||latestSnapshotRecord.accountId||'');if(!accountId)return[];
    if(this.planService&&Date.now()-this.lastResetCheck>60000){this.lastResetCheck=Date.now();await this.planService.automaticResets().catch((error)=>this.logger.warn?.('Daily Plan reset check failed',{message:error.message}));}
    const snapshot=latestSnapshotRecord.snapshot||{};
    return [...await this.ingestPlanRules(accountId,snapshot),...await this.ingestBehaviors(accountId,snapshot)];
  }

  async ingestPlanRules(accountId,snapshot) {
    const m=metrics(snapshot);const r=await this.pool.query(`SELECT r.*,p.account_ids FROM wisdo_plan_rules r JOIN wisdo_daily_plans p ON p.plan_id=r.plan_id WHERE p.status='ACTIVE' AND r.status='ARMED' AND r.supported=TRUE AND $1=ANY(p.account_ids)`,[accountId]);const events=[];
    for(const rule of r.rows){if(!this.condition(rule,m)){await this.pool.query(`INSERT INTO wisdo_conditional_rule_state(rule_id,owner_user_id,account_id,state,last_value,last_checked_at) VALUES($1,$2,$3,'ARMED',$4,NOW()) ON CONFLICT(rule_id) DO UPDATE SET last_value=EXCLUDED.last_value,last_checked_at=NOW(),updated_at=NOW()`,[rule.rule_id,rule.owner_user_id,accountId,m.drawdownPercent]);continue;}const claimed=await this.pool.query(`UPDATE wisdo_plan_rules SET status='TRIGGERED',updated_at=NOW() WHERE rule_id=$1 AND status='ARMED' RETURNING *`,[rule.rule_id]);if(!claimed.rowCount)continue;const actions=rule.parameters?.actions||[];for(const action of actions){if(!ACTION_COMMANDS[action])continue;try{const command=await this.executionService.queue({userId:rule.owner_user_id,accountId,intent:action,commandName:ACTION_COMMANDS[action],parameters:{planRuleId:rule.rule_id},rawText:`Daily Plan rule ${rule.rule_type}`,safetyLevel:'CONTROLLED',planId:rule.plan_id,confirmationStatus:'CONFIRMED'});events.push({ruleId:rule.rule_id,action,commandId:command.id});}catch(error){events.push({ruleId:rule.rule_id,action,error:error.message});}}await this.pool.query(`INSERT INTO wisdo_plan_execution_events(event_id,plan_id,rule_id,owner_user_id,event_type,detail) VALUES(gen_random_uuid(),$1,$2,$3,'RULE_TRIGGERED',$4::jsonb)`,[rule.plan_id,rule.rule_id,rule.owner_user_id,JSON.stringify({metrics:m,events})]);}return events;
  }

  async ingestBehaviors(accountId,snapshot,now=new Date()) {
    const result=await this.pool.query(`SELECT * FROM wisdo_behaviors WHERE status='active' AND scope->>'account_id'=$1 AND definition->'trigger'->>'type'='resettable_inactivity_timer' AND (expires_at IS NULL OR expires_at>NOW())`,[accountId]);const events=[];
    for(const row of result.rows)events.push(...await this.evaluateResettableTimer(row,accountId,snapshot,now));return events;
  }

  async evaluateResettableTimer(row,accountId,snapshot,now=new Date()) {
    const definition=row.definition||{},timeoutSeconds=Math.max(1,Number(definition.trigger?.timeout_seconds||0));if(!Number.isFinite(timeoutSeconds)||timeoutSeconds<=0)return[];
    const trades=openTrades(snapshot),tickets=ticketSet(trades),profit=basketProfit(trades);const priorResult=await this.pool.query(`SELECT * FROM wisdo_behavior_runtime_state WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId]);const prior=priorResult.rows[0];const priorTickets=Array.isArray(prior?.open_tickets)?prior.open_tickets.map(String):[];const newTickets=tickets.filter((ticket)=>!priorTickets.includes(ticket));const reset=Boolean(newTickets.length)||!prior;const deadline=reset?new Date(now.getTime()+timeoutSeconds*1000):new Date(prior.deadline_at);const metadata={newTickets,basketProfit:profit,openCount:tickets.length};
    if(reset||now<deadline||prior?.state==='FIRED'){await this.pool.query(`INSERT INTO wisdo_behavior_runtime_state(behavior_id,owner_user_id,account_id,state,open_tickets,last_entry_at,deadline_at,last_checked_at,metadata) VALUES($1,$2,$3,'ARMED',$4::jsonb,$5,$6,$5,$7::jsonb) ON CONFLICT(behavior_id,account_id) DO UPDATE SET state=CASE WHEN wisdo_behavior_runtime_state.state='FIRED' THEN 'FIRED' ELSE 'ARMED' END,open_tickets=EXCLUDED.open_tickets,last_entry_at=CASE WHEN $8 THEN EXCLUDED.last_entry_at ELSE wisdo_behavior_runtime_state.last_entry_at END,deadline_at=CASE WHEN $8 THEN EXCLUDED.deadline_at ELSE wisdo_behavior_runtime_state.deadline_at END,last_checked_at=EXCLUDED.last_checked_at,metadata=EXCLUDED.metadata,updated_at=NOW()`,[row.behavior_id,row.owner_user_id,accountId,JSON.stringify(tickets),now,deadline,JSON.stringify(metadata),reset]);return reset&&newTickets.length?[{behaviorId:row.behavior_id,event:'timer_reset',newTickets,deadlineAt:deadline.toISOString()}]:[];}
    if(!tickets.length||profit<=0){await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET open_tickets=$3::jsonb,last_checked_at=$4,metadata=$5::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId,JSON.stringify(tickets),now,JSON.stringify({...metadata,blockedReason:!tickets.length?'no_open_trades':'basket_not_profitable'})]);return [{behaviorId:row.behavior_id,event:'timeout_blocked',reason:!tickets.length?'no_open_trades':'basket_not_profitable'}];}
    const claimed=await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='FIRED',last_checked_at=$3,last_triggered_at=$3,metadata=$4::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2 AND state='ARMED' RETURNING *`,[row.behavior_id,accountId,now,JSON.stringify({...metadata,targetTickets:tickets})]);if(!claimed.rowCount)return[];
    try{const command=await this.executionService.queue({userId:row.owner_user_id,accountId,intent:'PROTECT_PROFIT_FULL_BASKET',commandName:'CLOSE_ALL_TRADES',parameters:{behaviorId:row.behavior_id,targetTickets:tickets,atomic:true,requirePositiveBasket:true,idempotencyKey:`behavior:${row.behavior_id}:${deadline.toISOString()}`},rawText:row.source_text||'Resettable entry protection timer',safetyLevel:'DANGEROUS',confirmationStatus:'CONFIRMED'});return [{behaviorId:row.behavior_id,event:'full_basket_close_queued',commandId:command.id,targetTickets:tickets,basketProfit:profit}];}
    catch(error){await this.pool.query(`UPDATE wisdo_behavior_runtime_state SET state='FAILED',metadata=metadata||$3::jsonb,updated_at=NOW() WHERE behavior_id=$1 AND account_id=$2`,[row.behavior_id,accountId,JSON.stringify({failure:error.message,targetTickets:tickets})]);return [{behaviorId:row.behavior_id,event:'execution_failed',error:error.message}];}
  }
}
