import { randomUUID } from 'node:crypto';

export const PLAN_STATES = Object.freeze(['DRAFT','AWAITING_INFORMATION','AWAITING_CONFIRMATION','ACTIVE','PAUSED','COMPLETED','CANCELLED','FAILED']);
const TRANSITIONS = Object.freeze({ DRAFT:['AWAITING_INFORMATION','AWAITING_CONFIRMATION','CANCELLED'], AWAITING_INFORMATION:['DRAFT','AWAITING_CONFIRMATION','CANCELLED'], AWAITING_CONFIRMATION:['ACTIVE','DRAFT','CANCELLED','FAILED'], ACTIVE:['PAUSED','COMPLETED','CANCELLED','FAILED'], PAUSED:['ACTIVE','CANCELLED','COMPLETED','FAILED'], COMPLETED:[], CANCELLED:[], FAILED:['DRAFT','CANCELLED'] });

export function defaultDailyPlan(userId, input = {}) { return { planId: input.planId || randomUUID(), name: input.name || "Today's Plan", status:'DRAFT', userId, accountIds:[], botIds:[], copierLanes:[], symbols:[], timeframes:[], directions:[], risk:{mode:null,value:null}, limits:{maxOpenTrades:null,maxLadderEntries:null,maxDailyLossUsd:null,maxDrawdownPercent:null,equityFloorUsd:null}, targets:{dailyProfitUsd:null,dailyProfitPercent:null,balanceTargetUsd:null,equityTargetUsd:null}, targetActions:[], resetPolicy:'NEXT_TRADING_DAY', timezone:'America/New_York', tradingDays:[1,2,3,4,5], automaticReset:false, parentPlanId:null, rawConversation:[], confirmation:{required:true,confirmedBy:null,confirmedAt:null}, ...input }; }

export function validateDailyPlan(plan) {
  const errors=[]; if (!PLAN_STATES.includes(plan?.status)) errors.push('invalid_status'); if (!plan?.userId) errors.push('user_required');
  if (!Array.isArray(plan?.accountIds)) errors.push('account_ids_required');
  if (plan?.risk?.value !== null && (!Number.isFinite(Number(plan.risk.value)) || Number(plan.risk.value)<0 || Number(plan.risk.value)>100)) errors.push('invalid_risk');
  return { ok:errors.length===0,errors,plan };
}

function merge(base, patch) { const out={...base,...patch}; for (const key of ['risk','limits','targets']) if (patch[key]) out[key]={...(base[key]||{}),...patch[key]}; for (const key of ['accountIds','botIds','copierLanes','symbols','timeframes','directions','targetActions']) if (patch[key]) out[key]=[...new Set(patch[key])]; return out; }

export class WisdoPlanService {
  constructor({ pool }={}) { this.pool=pool; }
  async create(userId,input={}) {
    const versionResult=await this.pool.query('SELECT COALESCE(MAX(version),0)+1 AS version FROM wisdo_daily_plans WHERE owner_user_id=$1 AND name=$2',[userId,input.name||"Today's Plan"]);
    const p=defaultDailyPlan(userId,{...input,version:Number(input.version||versionResult.rows[0]?.version||1)});
    const v=validateDailyPlan(p);
    if(!v.ok) throw Object.assign(new Error(v.errors.join(',')),{code:'invalid_plan'});
    const r=await this.pool.query(`INSERT INTO wisdo_daily_plans(plan_id,owner_user_id,name,version,status,account_ids,bot_ids,copier_lanes,symbols,timeframes,directions,risk,limits,targets,target_actions,reset_policy,raw_conversation,confirmation_required,timezone,trading_days,automatic_reset,parent_plan_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14::jsonb,$15,$16,$17::jsonb,$18,$19,$20,$21,$22) RETURNING *`,[p.planId,userId,p.name,p.version,p.status,p.accountIds,p.botIds,p.copierLanes,p.symbols,p.timeframes,p.directions,JSON.stringify(p.risk),JSON.stringify(p.limits),JSON.stringify(p.targets),p.targetActions,p.resetPolicy,JSON.stringify(p.rawConversation),p.confirmation.required,p.timezone,p.tradingDays,p.automaticReset,p.parentPlanId]);
    const created=this.toModel(r.rows[0]); await this.snapshot(created,'created'); return created;
  }
  toModel(row){ if(!row)return null; return defaultDailyPlan(row.owner_user_id,{planId:row.plan_id,name:row.name,status:row.status,accountIds:row.account_ids,botIds:row.bot_ids,copierLanes:row.copier_lanes,symbols:row.symbols,timeframes:row.timeframes,directions:row.directions,risk:row.risk,limits:row.limits,targets:row.targets,targetActions:row.target_actions,resetPolicy:row.reset_policy,timezone:row.timezone||'America/New_York',tradingDays:row.trading_days||[1,2,3,4,5],automaticReset:Boolean(row.automatic_reset),parentPlanId:row.parent_plan_id||null,rawConversation:row.raw_conversation,confirmation:{required:row.confirmation_required,confirmedBy:row.confirmed_by,confirmedAt:row.confirmed_at},version:row.version,activatedAt:row.activated_at,completedAt:row.completed_at}); }
  async get(userId,planId){const r=await this.pool.query(`SELECT * FROM wisdo_daily_plans WHERE plan_id=$1 AND owner_user_id=$2`,[planId,userId]);return this.toModel(r.rows[0]);}
  async active(userId){const r=await this.pool.query(`SELECT * FROM wisdo_daily_plans WHERE owner_user_id=$1 AND status IN ('DRAFT','AWAITING_INFORMATION','AWAITING_CONFIRMATION','ACTIVE','PAUSED') ORDER BY updated_at DESC LIMIT 1`,[userId]);return this.toModel(r.rows[0]);}
  async modify(userId,planId,patch,rawText=''){ const current=await this.get(userId,planId); if(!current)throw Object.assign(new Error('Plan not found.'),{code:'plan_not_found'}); const next=merge(current,patch); if(rawText)next.rawConversation=[...current.rawConversation,{role:'user',content:rawText,at:new Date().toISOString()}].slice(-50); const r=await this.pool.query(`UPDATE wisdo_daily_plans SET account_ids=$3,bot_ids=$4,copier_lanes=$5,symbols=$6,timeframes=$7,directions=$8,risk=$9::jsonb,limits=$10::jsonb,targets=$11::jsonb,target_actions=$12,raw_conversation=$13::jsonb,timezone=$14,trading_days=$15,automatic_reset=$16,updated_at=NOW() WHERE plan_id=$1 AND owner_user_id=$2 RETURNING *`,[planId,userId,next.accountIds,next.botIds,next.copierLanes,next.symbols,next.timeframes,next.directions,JSON.stringify(next.risk),JSON.stringify(next.limits),JSON.stringify(next.targets),next.targetActions,JSON.stringify(next.rawConversation),next.timezone,next.tradingDays,next.automaticReset]);const saved=this.toModel(r.rows[0]);await this.snapshot(saved,'modified');return saved; }
  async transition(userId,planId,status,actor=userId){const p=await this.get(userId,planId);if(!p)throw new Error('Plan not found.');if(!(TRANSITIONS[p.status]||[]).includes(status))throw Object.assign(new Error(`Invalid plan transition ${p.status} -> ${status}.`),{code:'invalid_plan_transition'});const r=await this.pool.query(`UPDATE wisdo_daily_plans SET status=$3,confirmed_by=CASE WHEN $3='ACTIVE' THEN $4 ELSE confirmed_by END,confirmed_at=CASE WHEN $3='ACTIVE' THEN NOW() ELSE confirmed_at END,activated_at=CASE WHEN $3='ACTIVE' THEN COALESCE(activated_at,NOW()) ELSE activated_at END,completed_at=CASE WHEN $3='COMPLETED' THEN NOW() ELSE completed_at END,updated_at=NOW() WHERE plan_id=$1 AND owner_user_id=$2 RETURNING *`,[planId,userId,status,actor]);if(['PAUSED','CANCELLED','COMPLETED','FAILED'].includes(status))await this.pool.query(`UPDATE wisdo_plan_rules SET status='CANCELLED',updated_at=NOW() WHERE plan_id=$1 AND owner_user_id=$2 AND status IN ('PENDING','ARMED')`,[planId,userId]);const saved=this.toModel(r.rows[0]);await this.snapshot(saved,`status:${status}`);return saved;}
  async snapshot(plan,reason){if(!this.pool||!plan)return;await this.pool.query(`INSERT INTO wisdo_plan_versions(version_id,plan_id,owner_user_id,version,snapshot,reason) VALUES($1,$2,$3,(SELECT COALESCE(MAX(version),0)+1 FROM wisdo_plan_versions WHERE plan_id=$2),$4::jsonb,$5)`,[randomUUID(),plan.planId,plan.userId,JSON.stringify(plan),reason]);}
  async history(userId,planId){return (await this.pool.query(`SELECT version,reason,snapshot,created_at FROM wisdo_plan_versions WHERE owner_user_id=$1 AND plan_id=$2 ORDER BY version DESC`,[userId,planId])).rows;}
  async duplicate(userId,planId,name){const source=await this.get(userId,planId);if(!source)throw Object.assign(new Error('Plan not found.'),{code:'plan_not_found'});return this.create(userId,{...source,planId:randomUUID(),name:name||`${source.name} Copy`,status:'DRAFT',parentPlanId:source.planId,rawConversation:[],confirmation:{required:true}});}
  async summary(userId,planId){const plan=await this.get(userId,planId);if(!plan)return null;const [rules,events]=await Promise.all([this.pool.query(`SELECT status,count(*)::int count FROM wisdo_plan_rules WHERE owner_user_id=$1 AND plan_id=$2 GROUP BY status`,[userId,planId]),this.pool.query(`SELECT event_type,detail,created_at FROM wisdo_plan_execution_events WHERE owner_user_id=$1 AND plan_id=$2 ORDER BY created_at DESC LIMIT 100`,[userId,planId])]);return {plan,ruleCounts:rules.rows,events:events.rows};}
  async resetForNextTradingDay(userId,planId,now=new Date()){const source=await this.get(userId,planId);if(!source||!source.automaticReset||!['COMPLETED','CANCELLED'].includes(source.status))return null;const weekday=Number(new Intl.DateTimeFormat('en-US',{timeZone:source.timezone,weekday:'short'}).format(now).replace(/Sun|Mon|Tue|Wed|Thu|Fri|Sat/,x=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(x)));if(!source.tradingDays.includes(weekday))return null;return this.create(userId,{...source,planId:randomUUID(),name:source.name,status:'DRAFT',parentPlanId:source.planId,rawConversation:[],confirmation:{required:true}});}
  async automaticResets(now=new Date()){const r=await this.pool.query(`SELECT p.* FROM wisdo_daily_plans p WHERE p.automatic_reset=TRUE AND p.status IN ('COMPLETED','CANCELLED') AND NOT EXISTS(SELECT 1 FROM wisdo_daily_plans child WHERE child.parent_plan_id=p.plan_id) ORDER BY p.completed_at NULLS LAST,p.updated_at LIMIT 25`);const created=[];for(const row of r.rows){const plan=await this.resetForNextTradingDay(row.owner_user_id,row.plan_id,now);if(plan)created.push(plan);}return created;}
  readBack(p){const accounts=p.accountIds.length?p.accountIds.join(', '):'your selected account';const pieces=[`use ${accounts}`];if(p.symbols.length)pieces.push(`on ${p.symbols.join(', ')}`);if(p.risk?.value!=null)pieces.push(`at ${p.risk.value}-percent risk`);if(p.limits?.maxDrawdownPercent!=null)pieces.push(`stop adding trades at ${p.limits.maxDrawdownPercent}-percent drawdown`);if(p.targets?.dailyProfitUsd!=null)pieces.push(`target $${p.targets.dailyProfitUsd} daily profit`);if(p.targetActions.length)pieces.push(`then ${p.targetActions.map(x=>x.toLowerCase().replaceAll('_',' ')).join(', ')}`);return `Here is today's plan: ${pieces.join('. ')}. Say â€œConfirm Coach, activate today's planâ€ to proceed.`;}
  unsupportedRules(p){return p.targetActions.filter((a)=>/^LEAVE_|^TRAIL_/.test(a));}
  compileRules(p){const rules=[];if(p.risk?.value!=null)rules.push({type:'RISK_PERCENT',parameters:{value:p.risk.value,immediate:true},supported:true,commandName:'CEM_SET_GLOBALS'});if(p.directions?.length)rules.push({type:'TRADE_DIRECTIONS',parameters:{directions:p.directions,immediate:true},supported:true,commandName:'CEM_SET_GLOBALS'});if(p.limits?.maxDrawdownPercent!=null)rules.push({type:'MAX_DRAWDOWN_PERCENT',parameters:{threshold:p.limits.maxDrawdownPercent,actions:['STOP_NEW_ENTRIES']},supported:true});if(p.limits?.maxDailyLossUsd!=null)rules.push({type:'MAX_DAILY_LOSS_USD',parameters:{threshold:p.limits.maxDailyLossUsd,actions:['STOP_NEW_ENTRIES']},supported:true});if(p.targets?.dailyProfitUsd!=null)rules.push({type:'DAILY_PROFIT_USD',parameters:{threshold:p.targets.dailyProfitUsd,actions:p.targetActions},supported:true});for(const action of this.unsupportedRules(p))rules.push({type:action,parameters:{},supported:false});return rules;}
  async materialize(userId,planId){const p=await this.get(userId,planId);if(!p)throw new Error('Plan not found.');const rows=[];for(const rule of this.compileRules(p)){const id=randomUUID();const r=await this.pool.query(`INSERT INTO wisdo_plan_rules(rule_id,plan_id,owner_user_id,rule_type,parameters,status,supported,command_name) VALUES($1,$2,$3,$4,$5::jsonb,'ARMED',$6,$7) ON CONFLICT(plan_id,rule_type) DO UPDATE SET parameters=EXCLUDED.parameters,supported=EXCLUDED.supported,command_name=EXCLUDED.command_name,updated_at=NOW() RETURNING *`,[id,planId,userId,rule.type,JSON.stringify(rule.parameters),rule.supported,rule.commandName||null]);if(r.rows[0])rows.push(r.rows[0]);}return rows;}
}
