// Shared settings surfaces for the current /app portal. Existing member APIs own persistence.
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sectionHero = (title, description, badges = '') => `<section class="card"><h2>${esc(title)}</h2><p>${description}</p>${badges}</section>`;

export function ambientSettingsPage() {
  const sections = [
    ['Homes & devices', '/app/smart-home', 'Create separate homes, bind trusted adapters, assign aliases and rooms, review discoveries, and approve devices.'],
    ['Rooms & privacy', '/app/life-os#rooms', 'Name the spaces WISDO coordinates and record their privacy level. Physical privacy controls depend on device support.'],
    ['Household & temporary access', '/app/life-os#household', 'Define adult, child, guest and technician mission roles, with an expiry for temporary records.'],
    ['Modes, missions & workstations', '/app/life-os#missions', 'Save reusable routines combining a mode, approved home scene, enrolled workstation and optional trading pause. Simulate before running.'],
    ['House laws', '/app/life-os#policies', 'Add restrictions and confirmation rules. Presence cannot authorize live trading.'],
    ['Presence awareness', '/app/presence', 'Configure the existing presence system. Sensor activity supplies context; it does not grant ownership or trading authority.'],
    ['Truth ledger', '/app/life-os#truth', 'Review simulation, blocked, queued, failed and completed events separately.'],
    ['Offline readiness', '/app/life-os#offline', 'Inspect local-safe manifest preparation. The offline edge runner is not available in V23.'],
  ];
  return `<section class="card"><span class="eyebrow">Settings</span><h2>Ambient Life OS</h2><p>Your physical home, digital workspace and trading environment, coordinated through approved missions.</p><p>Saving settings does not run a mission or activate trading.</p></section><div class="grid2" style="margin-top:16px">${sections.map(([name,href,description])=>`<section class="card"><h3>${name}</h3><p>${description}</p><a class="btn" href="${href}">Open ${name}</a></section>`).join('')}</div><section class="card" style="margin-top:16px"><h3>Not available yet</h3><p>Follow-me voice, vehicle handoff, house digital twin, learned voice identity, local voice inference, automatic network recovery and emergency orchestration do not have active controls in this release.</p></section>`;
}

function securityPrivacyPageContent() {
  return `${sectionHero('Security & Privacy', 'Identity, device trust, household access, privacy zones, and verified outcomes live here. Presence and nearby devices never grant authority.', '<span class="tag">Fail closed</span><span class="tag">Presence ≠ permission</span><span class="tag">Truth receipts</span>')}
  <div class="grid"><section class="card ok"><h3>Identity & access</h3><div class="metric">Session protected</div><p class="muted">An authenticated member session is required for homes, rooms, missions, and security settings.</p><a class="btn" href="/app/life-os#household">Manage household roles</a></section><section class="card"><h3>Device trust</h3><div class="metric">Approval required</div><p class="muted">Only devices from a bound source and owned WISDO Home can become controllable.</p><a class="btn" href="/app/smart-home">Review device inbox</a></section><section class="card warn"><h3>Physical security</h3><div class="metric">Confirmation required</div><p class="muted">Locks, alarms, garages, sirens, cameras, and other sensitive actions keep an explicit confirmation gate.</p></section><section class="card"><h3>Trading boundary</h3><div class="metric">Presence blocked</div><p class="muted">Presence and unattended routines cannot mutate live trading. Trading steps must be simulated and confirmed.</p><a class="btn" href="/app/life-os#policies">Review house laws</a></section></div>
  <div class="grid2" style="margin-top:16px"><section class="card"><h3>Privacy zones</h3><p class="muted">Bedrooms, cameras, microphones, trading screens, and family areas can carry stricter privacy levels where approved hardware supports them.</p><a class="btn" href="/app/life-os#rooms">Configure room privacy</a></section><section class="card"><h3>Truth ledger</h3><p class="muted">Intent, policy checks, queueing, device acknowledgement, failure, and completion stay separate. Sent does not mean completed without a receipt.</p><a class="btn" href="/app/life-os#truth">Open truth ledger</a></section></div>
  <section class="card full" style="margin-top:16px"><h3>Emergency protections</h3><p>WISDO does not silently unlock doors, disarm alarms, open garages, disable cameras, or start trading from an alarm or presence event.</p><span class="tag">No automatic unlock</span><span class="tag">No automatic disarm</span><span class="tag">No sensor-triggered live trade</span></section>`;
}

function smartHomeTrustCenterPageContent() {
  return `${sectionHero('Smart Home Trust Center', 'Discover broadly, trust carefully. Devices can appear here from approved hubs and adapters, but nothing becomes controllable until it is bound to your Home and explicitly approved.', '<span class="tag">Discovery ≠ authorization</span><span class="tag">Proximity ≠ ownership</span>')}
  <div class="grid" id="homeMetrics"><section class="card"><h3>Pending</h3><div class="metric" id="pendingCount">—</div><div class="muted">Quarantined discoveries</div></section><section class="card"><h3>Approved</h3><div class="metric green" id="approvedCount">—</div><div class="muted">Controllable devices</div></section><section class="card"><h3>Sources</h3><div class="metric" id="sourceCount">—</div><div class="muted">Hub / adapter sources</div></section><section class="card"><h3>Duplicate Review</h3><div class="metric gold" id="duplicateCount">—</div><div class="muted">Never auto-merged</div></section></div>
  <div class="grid2" style="margin-top:16px">
    <section class="card"><h3>1. Create or select your WISDO Home</h3><p>Approval is tied to a home you own, not to nearby radio signals.</p><div class="row"><input id="homeName" placeholder="Example: Fountain Home" style="min-width:240px"><button class="btn primary" id="createHome" type="button">Create Home</button></div><div id="homesList" class="muted" style="margin-top:10px"></div></section>
    <section class="card"><h3>2. Bind trusted hubs/controllers</h3><p>A discovered Home Assistant, Z-Wave, Zigbee, Matter, or other source must be bound to one of your Homes before its devices can be approved.</p><div id="sourceList" class="muted">Loading sources…</div></section>
  </div>
  <section class="card full" style="margin-top:16px"><div class="row" style="justify-content:space-between"><div><h3>3. Pending Device Inbox</h3><p>Rename, assign a room, add aliases, then approve only the devices you recognize.</p></div><div class="row"><select id="batchHome"></select><button class="btn primary" id="approveSelected" type="button">Approve Selected</button></div></div><div style="overflow:auto"><table><thead><tr><th></th><th>Device</th><th>Class / Adapter</th><th>Room</th><th>Aliases</th><th>State</th><th>Action</th></tr></thead><tbody id="pendingRows"><tr><td colspan="7">Loading…</td></tr></tbody></table></div></section>
  <section class="card full" style="margin-top:16px"><h3>Approved Devices</h3><p class="muted">Approved devices can be resolved by WISDO voice/text/presence rules. Physical-security actions still require confirmation.</p><div style="overflow:auto"><table><thead><tr><th>Device</th><th>Class</th><th>Room</th><th>Adapter</th><th>Status</th><th>Action</th></tr></thead><tbody id="approvedRows"><tr><td colspan="6">Loading…</td></tr></tbody></table></div></section>
  <section class="card full" style="margin-top:16px"><h3>Possible Duplicates</h3><p class="muted">WISDO flags likely duplicates but never merges them automatically.</p><div id="duplicatesBox">Loading…</div></section>
  <section class="card full" style="margin-top:16px"><h3>Old / Unknown Device Compatibility Adviser</h3><p>Tell WISDO what kind of device and connection you have. It will recommend bridge paths without pretending unsupported hardware is directly controllable.</p><div class="row"><select id="compatClass"><option>THERMOSTAT</option><option>LIGHT</option><option>LOCK</option><option>GARAGE</option><option>FAN</option><option>MEDIA</option><option>IR_APPLIANCE</option><option>RF_APPLIANCE</option><option>RELAY</option><option>GENERIC</option></select><select id="compatProtocol"><option value="z-wave">Z-Wave</option><option value="zigbee">Zigbee</option><option value="matter">Matter</option><option value="thread">Thread</option><option value="wifi">Wi-Fi</option><option value="bluetooth">Bluetooth</option><option value="ir">IR</option><option value="rf">RF</option><option value="relay">Relay / dry contact</option><option value="modbus">Modbus</option><option value="bacnet">BACnet</option><option value="unknown">I don't know</option></select><button class="btn primary" id="checkCompatibility" type="button">Find Safe Path</button></div><pre id="compatibilityOut" class="checkout-result" style="display:block;min-height:72px">Choose a device class and protocol.</pre></section>
  <section class="card ok full" style="margin-top:16px"><h3>Trust Policy</h3><p>Nearby devices are ignored unless an authenticated adapter exposes them. Adapter discovery still does not grant control. Approval requires an owned Home and a bound source. Locks, alarms, garages, sirens, cameras, and other sensitive actions keep their existing safety gates.</p></section>
  <script src="/js/smart-home-trust-center.js" defer></script>`;
}

function ambientLifeOsPageContent() {
  return `${sectionHero('WISDO Ambient Life OS', 'Coordinate home, rooms, household roles, workstations, trading controls, modes, policies, and truth receipts as one mission system. Every mission can be simulated before execution.', '<span class="tag">V23</span><span class="tag">Simulation first</span><span class="tag">Truth ledger</span>')}
  <nav class="actions" aria-label="Ambient Life sections"><a class="btn" href="/app/settings">All settings</a><a class="btn" href="/app/smart-home">Homes & devices</a><a class="btn" href="#rooms">Rooms & privacy</a><a class="btn" href="#household">Household</a><a class="btn" href="#missions">Modes & missions</a><a class="btn" href="#policies">House laws</a><a class="btn" href="#truth">Truth ledger</a></nav><p id="ambientHomeStatus" role="status">Loading your homes…</p>
  <div class="grid"><section class="card"><h3>Missions</h3><div class="metric" id="missionCount">—</div><div class="muted">Cross-domain mission definitions</div></section><section class="card"><h3>Zones</h3><div class="metric" id="zoneCount">—</div><div class="muted">Room/privacy zones</div></section><section class="card"><h3>Household</h3><div class="metric" id="householdCount">—</div><div class="muted">Active permission identities</div></section><section class="card"><h3>Recent Runs</h3><div class="metric" id="runCount">—</div><div class="muted">Truth-tracked executions</div></section></div>
  <div class="grid2" style="margin-top:16px">
    <section class="card" id="missions"><h3>Modes & Mission Composer</h3><p>Create a mission that can coordinate WISDO modes, Home Assistant scenes, your workstation, and supported trading controls. Simulation still decides what is actually allowed.</p><input id="missionName" placeholder="Start My Trading Day"><textarea id="missionDescription" rows="2" placeholder="What should this mission accomplish?"></textarea><label>Home<select id="missionHomeId" data-ambient-home><option value="">Choose a home</option></select></label><div class="row"><select id="missionMode"><option value="trading">Trading</option><option value="focus">Focus</option><option value="family">Family</option><option value="relax">Relax</option><option value="sleep">Sleep</option><option value="away">Away</option><option value="guest">Guest</option></select><input id="missionScene" placeholder="Optional Home Assistant scene alias"></div><input id="missionAccount" placeholder="Optional trading account ID"><label><input id="missionWorkstation" type="checkbox"> Prepare trading workstation</label><br><label><input id="missionPauseTrading" type="checkbox"> Pause new trading entries</label><div style="margin-top:10px"><button class="btn primary" id="createMission" type="button">Create Mission</button></div></section>
    <section class="card"><h3>Mission Simulation / Execution</h3><pre id="missionOutput" class="checkout-result" style="display:block;min-height:290px;max-height:420px;overflow:auto">Select a mission below and simulate it before execution.</pre></section>
  </div>
  <div class="grid2" style="margin-top:16px">
    <section class="card" id="rooms"><h3>Room & Privacy Zones</h3><p>Privacy levels label room sensitivity. They do not physically disable microphones or cameras.</p><div class="row"><label>Home<select id="zoneHomeId" data-ambient-home><option value="">Choose a home</option></select></label><input id="zoneName" placeholder="Trading Room"></div><div class="row"><select id="zonePrivacy"><option value="1">Privacy 1 · Normal</option><option value="2">Privacy 2</option><option value="3">Privacy 3</option><option value="4">Privacy 4</option><option value="5">Privacy 5 · Restricted</option></select><button class="btn" id="createZone" type="button">Add Zone</button></div><div id="zonesList" style="margin-top:10px"></div></section>
    <section class="card" id="household"><h3>Household Permissions</h3><p>These records define mission roles; they do not enroll a voice identity or grant website login access. Guest and technician records require an expiry here.</p><div class="row"><label>Home<select id="memberHomeId" data-ambient-home><option value="">Choose a home</option></select></label><input id="memberName" placeholder="Display name"></div><label>Access expires (your local time)<input id="memberExpires" type="datetime-local"></label><div class="row"><select id="memberRole"><option>ADULT</option><option>CHILD</option><option>GUEST</option><option>TECHNICIAN</option></select><button class="btn" id="addHousehold" type="button">Add Member</button></div><div id="householdList" style="margin-top:10px"></div></section>
  </div>
  <section class="card full" style="margin-top:16px"><h3>Mission Library</h3><p class="muted">A mission can be simulated without touching any device. Running still enforces Home ownership, approved devices, role permissions, physical-security confirmation, trading authorization, and adapter availability.</p><div id="missionsList">Loading…</div></section>
  <section class="card full" id="policies" style="margin-top:16px"><h3>House Laws / Policy Guardrails</h3><p>Baseline policies always apply. Add a rule that blocks an action or requires confirmation.</p><form id="ambientPolicyForm"><label>Home<select id="policyHomeId" data-ambient-home required><option value="">Choose a home</option></select></label><label>Rule name<input id="policyName" maxlength="120" required></label><label>Rule<select id="policyPreset"><option value="security">Never unlock, disarm or open through missions</option><option value="camera">Block camera actions through missions</option><option value="trading">Require confirmation for trading steps</option><option value="home">Require confirmation for all home steps</option></select></label><button class="btn" type="submit">Save house rule</button><p id="policyStatus" role="status"></p></form><div id="policyList">Loading…</div></section>
  <section class="card full" id="truth" style="margin-top:16px"><h3>Truth Ledger</h3><p class="muted">WISDO records simulation, blocked states, confirmation requirements, queued actions, failures, and completions separately. Queued is never presented as physically completed.</p><div id="truthList">Loading…</div></section>
  <section class="card warn full" id="offline" style="margin-top:16px"><h3>Local-First Status</h3><p>V23 can compile safe home-only missions into signed local manifests. The offline edge runner is deliberately not enabled yet, so a manifest is never presented as active offline automation until that runner is built and verified.</p></section>
  <script src="/js/ambient-life-os.js?v=23.1" defer></script>`;
}

const homeDesign = `<style>
.wisdo-home-view{--ink:#e3f5ff;--accent:#63e3ff;background:radial-gradient(ellipse at 90% 0%,#16345388,transparent 45%),linear-gradient(145deg,#071423,#030913);color:var(--ink);padding:clamp(16px,3vw,36px);border:1px solid #214158;border-radius:22px;font-family:Inter,Arial,sans-serif;line-height:1.6;isolation:isolate}
.wisdo-home-view *{box-sizing:border-box}.wisdo-home-view h2{font-size:clamp(26px,3.5vw,42px);line-height:1.15;letter-spacing:-.035em;color:var(--ink);margin:8px 0 18px}.wisdo-home-view h3{color:#e3f5ff;font-size:18px}.wisdo-home-view p,.wisdo-home-view .muted{color:#a8c2d5}
.wisdo-home-view .card{background:linear-gradient(135deg,#11263ae8,#07111eea);color:var(--ink);border:1px solid #26465e;border-radius:16px;padding:22px;margin-bottom:12px;box-shadow:inset 0 1px #80d7ff0b,0 12px 30px #0002;min-width:0}
.wisdo-home-view .grid,.wisdo-home-view .grid2,.wisdo-home-view .grid3{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,270px),1fr));gap:16px}
.wisdo-home-view .row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.wisdo-home-view .btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;background:#102c40;color:#a9efff;border:1px solid #37708c;border-radius:10px;padding:10px 18px;text-decoration:none;cursor:pointer;font:inherit;font-size:14px;transition:background .2s,border-color .2s}.wisdo-home-view .btn:hover{background:#18415a;border-color:#63e3ff}.wisdo-home-view .btn.primary{background:linear-gradient(110deg,#125c7e,#263f76);color:#fff;border-color:#60cce9}
.wisdo-home-view input,.wisdo-home-view select,.wisdo-home-view textarea{background:#050f1e;color:#dff5ff;border:1px solid #35536c;border-radius:8px;padding:12px;max-width:100%;color-scheme:dark;font:inherit;font-size:14px}.wisdo-home-view input::placeholder,.wisdo-home-view textarea::placeholder{color:#8ca5bb}.wisdo-home-view label{display:block;margin:12px 0;color:#bdd8e8}.wisdo-home-view label input,.wisdo-home-view label textarea{display:block;width:100%}.wisdo-home-view input[type=checkbox]{display:inline-block;width:auto;accent-color:#65dcff}.wisdo-home-view textarea{width:100%}
.wisdo-home-view .tag{display:inline-block;border:1px solid #294c65;border-radius:6px;padding:4px 10px;background:#0c2134;color:#9fdbed;margin:3px;font-size:12px}.wisdo-home-view .metric{color:#74e6ff;font-size:30px;font-weight:600;letter-spacing:-.025em}.wisdo-home-view .green{color:#72eac3}.wisdo-home-view .gold{color:#e8c584}
.wisdo-home-view nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:24px}.wisdo-home-view nav a{padding:10px 16px;border-radius:8px;text-decoration:none;color:#a5bed1;border:1px solid #263d51;background:#0b1929;font-size:14px}.wisdo-home-view nav a[aria-current]{background:#113650;color:#89ebff;border-color:#489ab5;box-shadow:0 0 20px #3edcff12}.wisdo-home-view a{color:#85dcff}
.wisdo-home-view .eyebrow{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#74dcff}.wisdo-home-view .home-command-hero{display:grid;grid-template-columns:1.2fr 1fr;align-items:center;gap:24px;padding:24px 8px 36px;position:relative}.wisdo-home-view .home-command-hero h2{font-size:clamp(32px,4vw,54px);max-width:600px}.wisdo-home-view .home-command-hero p{max-width:540px}.wisdo-home-view .home-visual{background:radial-gradient(ellipse,#13577555,transparent 65%);text-align:center}.wisdo-home-view .home-visual svg{width:100%;max-height:260px;filter:drop-shadow(0 0 10px #47ceff55)}.wisdo-home-view .home-visual small{color:#8ba9bf;font-size:11px}
.wisdo-home-view table{width:100%;border-collapse:collapse;font-size:14px}.wisdo-home-view th{text-align:left;color:#90bdd7;font-size:12px;letter-spacing:.04em}.wisdo-home-view td,.wisdo-home-view th{padding:12px;border-bottom:1px solid #243b50}.wisdo-home-view pre{background:#040d18;color:#a6d9ee;border:1px solid #26485f;border-radius:10px;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere}.wisdo-home-view .emergency{border-color:#856044}.wisdo-home-view .emergency-call{background:#702b34;color:#fff;border-color:#d4737d}.wisdo-home-view details{margin-top:20px}.wisdo-home-view summary{cursor:pointer;color:#afd8ee}.wisdo-home-view :focus-visible{outline:3px solid #be9aff;outline-offset:4px}.wisdo-home-view section[id]{scroll-margin-top:90px}
@media(max-width:600px){.wisdo-home-view{padding:14px;border-radius:12px}.wisdo-home-view .card{padding:16px}.wisdo-home-view nav{gap:6px}.wisdo-home-view nav a{padding:10px 12px}.wisdo-home-view .home-command-hero{grid-template-columns:1fr;padding:16px 0 24px;gap:8px}.wisdo-home-view .home-visual svg{max-height:180px}.wisdo-home-view .home-command-hero h2{font-size:34px}}
</style>`;
function homeCommandHero(active){
 const content={
 'smart-home':['SMART HOME','Your connected environment','Connect your home. Review discoveries. Decide which devices WISDO can control.','/app/smart-home#homeMetrics','Device overview'],
 'life-os':['AMBIENT LIFE','Coordinate your day','Build missions around your spaces, your household, and the way you work. Simulate each step before running.','/app/life-os#missions','Compose a mission'],
 security:['SECURITY','Awareness. Access. Control.','Manage trusted devices, household permissions, and privacy from one command space.','/app/life-os#household','Manage access']
 }[active];
 const house='<path d="M40 115 150 55 260 115 150 178Z" fill="#0b3148"/><path d="M60 105V70L150 24l90 46v35M60 70l90 49 90-49M150 119v59M60 105v45l90 48 90-48v-45M93 125V98l32 17v27M180 130v-28l34-17v29" stroke="#6de3ff" fill="#0a2237"/><path d="m40 155 110 59 110-59M20 170l130 70 130-70" stroke="#306888"/><path d="m150 119 44-24v45l-44 25" stroke="#b59bff" fill="#54419233"/>';
 const orbit='<ellipse cx="150" cy="115" rx="125" ry="48" transform="rotate(-28 150 115)" stroke="#65dcff"/><ellipse cx="150" cy="115" rx="125" ry="48" transform="rotate(28 150 115)" stroke="#b39bff"/><circle cx="150" cy="115" r="72" stroke="#3c7199" stroke-dasharray="3 7"/><circle cx="150" cy="115" r="43" fill="#12364f" stroke="#81e8ff"/><path d="m129 105 10 24 12-23 12 23 10-24" stroke="#b9f3ff" stroke-width="3"/><circle cx="49" cy="67" r="9" fill="#79ddff"/><circle cx="252" cy="162" r="9" fill="#b59aff"/><circle cx="195" cy="57" r="6" fill="#8bf2d1"/>';
 const shield='<path d="M150 20 237 52v68c0 48-48 82-87 103-39-21-87-55-87-103V52Z" fill="#0b293f" stroke="#6ee3ff" stroke-width="2"/><path d="m150 36 71 28v55c0 37-36 67-71 87-35-20-71-50-71-87V64Z" stroke="#446eaa"/><path d="m111 116 39-32 39 32v46h-78Z" fill="#17405a" stroke="#9deaff"/><path d="M140 162v-28h20v28" stroke="#bba0ff"/><path d="M32 80h20M248 80h20M32 166h20M248 166h20" stroke="#38728b"/>';
 return `<section class="home-command-hero"><div><span class="eyebrow">WISDO / ${content[0]}</span><h2>${content[1]}</h2><p>${content[2]}</p><a class="btn primary" href="${content[3]}">${content[4]} ↗</a></div><div class="home-visual"><svg viewBox="0 0 300 250" fill="none" stroke-width="1.5" aria-hidden="true">${active==='smart-home'?house:active==='life-os'?orbit:shield}</svg><small>Interface illustration · not device status</small></div></section>`;
}

function homeFrame(active, body) {
 const links=[['smart-home','Smart Home'],['life-os','Ambient Life'],['security','Security']];
 return homeDesign+`<div class="wisdo-home-view"><nav aria-label="Home workspace">${links.map(([key,label])=>`<a href="/app/${key}" ${key===active?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${homeCommandHero(active)}${body}</div>`;
}
function emergencyPanel(){return `<section class="card emergency"><span class="eyebrow">Emergency assistance</span><h2>Help from your phone</h2><p>For an emergency in the United States, use your phone to call 911. WISDO does not provide monitoring or dispatch confirmation.</p><a class="btn emergency-call" href="tel:911">Call 911 · United States</a><p>Your phone handles the call. Opening the phone app does not confirm a connection or police dispatch. Outside the US, use your local emergency number.</p><details><summary>Monitoring company and information for the dispatcher</summary><form id="emergencyPhoneForm"><label>Monitoring company phone number<input id="monitoringPhone" type="tel" autocomplete="tel" required maxlength="24" placeholder="Enter your provider’s number"></label><button class="btn" type="submit">Call monitoring company</button><p id="emergencyPhoneStatus" role="status" aria-live="polite"></p></form><label>Property address<textarea rows="2" autocomplete="street-address" placeholder="Enter the address to read to the dispatcher"></textarea></label><label>Relevant emergency information<textarea rows="3" placeholder="Describe the situation and where help is needed"></textarea></label><p>These notes stay on this page and are cleared when you leave. They are not sent to emergency services.</p></details></section><script>
(()=>{const form=document.getElementById('emergencyPhoneForm');form.addEventListener('submit',event=>{event.preventDefault();const raw=document.getElementById('monitoringPhone').value.trim();const status=document.getElementById('emergencyPhoneStatus');if(!/^[+]?[0-9 ()-]{7,24}$/.test(raw)){status.textContent='Enter a valid phone number, including the area code.';return;}const number=raw.replace(/[ ()-]/g,'');if(number.replace(/[^0-9]/g,'').length<7){status.textContent='Enter the complete monitoring company number.';return;}status.textContent='Call requested. Complete it in your phone app; connection is unverified.';window.location.href='tel:'+number;});})();
</script>`;}
export function securityPrivacyPage(){return homeFrame('security',emergencyPanel()+securityPrivacyPageContent());}
export function smartHomeTrustCenterPage(){return homeFrame('smart-home',smartHomeTrustCenterPageContent());}
export function ambientLifeOsPage(){return homeFrame('life-os',ambientLifeOsPageContent());}
