// Shared settings surfaces for the current /app portal. Existing member APIs own persistence.
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sectionHero = (title, description, badges = '') => `<section class="card"><h2>${esc(title)}</h2><p>${description}</p>${badges}</section>`;

export function ambientSettingsPage() {
  const sections = [
    ['Homes & devices', '/app/smart-home', 'Create separate homes, bind trusted adapters, assign aliases and rooms, review discoveries, and approve devices.'],
    ['Rooms & privacy', '/app/life-os#rooms', 'Name the spaces WISDO coordinates and record their privacy level. Physical privacy controls depend on device support.'],
    ['Household & temporary access', '/app/life-os#household', 'Define adult, child, guest and technician mission roles, with an expiry for temporary records.'],
    ['Modes, missions & workstations', '/app/life-os#missions', 'Save reusable routines combining a mode, approved home scene, enrolled workstation and optional trading pause. Simulate before running.'],
    ['House laws', '/app/life-os#policies', 'Add restrictions and confirmation rules. Presence cannot authorize live trading.'],
    ['Presence awareness', '/app/presence', 'Configure the existing presence system. Sensor activity supplies context; it does not grant ownership or trading authority.'],
    ['Truth ledger', '/app/life-os#truth', 'Review simulation, blocked, queued, failed and completed events separately.'],
    ['Offline readiness', '/app/life-os#offline', 'Inspect local-safe manifest preparation. The offline edge runner is not available in V23.'],
  ];
  return `<section class="card"><span class="eyebrow">Settings</span><h2>Ambient Life OS</h2><p>Your physical home, digital workspace and trading environment, coordinated through approved missions.</p><p>Saving settings does not run a mission or activate trading.</p></section><div class="grid2" style="margin-top:16px">${sections.map(([name,href,description])=>`<section class="card"><h3>${name}</h3><p>${description}</p><a class="btn" href="${href}">Open ${name}</a></section>`).join('')}</div><section class="card" style="margin-top:16px"><h3>Not available yet</h3><p>Follow-me voice, vehicle handoff, house digital twin, learned voice identity, local voice inference, automatic network recovery and emergency orchestration do not have active controls in this release.</p></section>`;
}

export function smartHomeTrustCenterPage() {
  return `${sectionHero('Smart Home Trust Center', 'Discover broadly, trust carefully. Devices can appear here from approved hubs and adapters, but nothing becomes controllable until it is bound to your Home and explicitly approved.', '<span class="tag">Discovery ≠ authorization</span><span class="tag">Proximity ≠ ownership</span>')}
  <div class="grid" id="homeMetrics"><section class="card"><h3>Pending</h3><div class="metric" id="pendingCount">—</div><div class="muted">Quarantined discoveries</div></section><section class="card"><h3>Approved</h3><div class="metric green" id="approvedCount">—</div><div class="muted">Controllable devices</div></section><section class="card"><h3>Sources</h3><div class="metric" id="sourceCount">—</div><div class="muted">Hub / adapter sources</div></section><section class="card"><h3>Duplicate Review</h3><div class="metric gold" id="duplicateCount">—</div><div class="muted">Never auto-merged</div></section></div>
  <div class="grid2" style="margin-top:16px">
    <section class="card"><h3>1. Create or select your WISDO Home</h3><p>Approval is tied to a home you own, not to nearby radio signals.</p><div class="row"><input id="homeName" placeholder="Example: Fountain Home" style="min-width:240px"><button class="btn primary" id="createHome" type="button">Create Home</button></div><div id="homesList" class="muted" style="margin-top:10px"></div></section>
    <section class="card"><h3>2. Bind trusted hubs/controllers</h3><p>A discovered Home Assistant, Z-Wave, Zigbee, Matter, or other source must be bound to one of your Homes before its devices can be approved.</p><div id="sourceList" class="muted">Loading sources…</div></section>
  </div>
  <section class="card full" style="margin-top:16px"><div class="row" style="justify-content:space-between"><div><h3>3. Pending Device Inbox</h3><p>Rename, assign a room, add aliases, then approve only the devices you recognize.</p></div><div class="row"><select id="batchHome"></select><button class="btn primary" id="approveSelected" type="button">Approve Selected</button></div></div><div style="overflow:auto"><table><thead><tr><th></th><th>Device</th><th>Class / Adapter</th><th>Room</th><th>Aliases</th><th>State</th><th>Action</th></tr></thead><tbody id="pendingRows"><tr><td colspan="7">Loading…</td></tr></tbody></table></div></section>
  <section class="card full" style="margin-top:16px"><h3>Approved Devices</h3><p class="muted">Approved devices can be resolved by WISDO voice/text/presence rules. Physical-security actions still require confirmation.</p><div style="overflow:auto"><table><thead><tr><th>Device</th><th>Class</th><th>Room</th><th>Adapter</th><th>Status</th><th>Action</th></tr></thead><tbody id="approvedRows"><tr><td colspan="6">Loading…</td></tr></tbody></table></div></section>
  <section class="card full" style="margin-top:16px"><h3>Possible Duplicates</h3><p class="muted">WISDO flags likely duplicates but never merges them automatically.</p><div id="duplicatesBox">Loading…</div></section>
  <section class="card full" style="margin-top:16px"><h3>Old / Unknown Device Compatibility Adviser</h3><p>Tell WISDO what kind of device and connection you have. It will recommend bridge paths without pretending unsupported hardware is directly controllable.</p><div class="row"><select id="compatClass"><option>THERMOSTAT</option><option>LIGHT</option><option>LOCK</option><option>GARAGE</option><option>FAN</option><option>MEDIA</option><option>IR_APPLIANCE</option><option>RF_APPLIANCE</option><option>RELAY</option><option>GENERIC</option></select><select id="compatProtocol"><option value="z-wave">Z-Wave</option><option value="zigbee">Zigbee</option><option value="matter">Matter</option><option value="thread">Thread</option><option value="wifi">Wi-Fi</option><option value="bluetooth">Bluetooth</option><option value="ir">IR</option><option value="rf">RF</option><option value="relay">Relay / dry contact</option><option value="modbus">Modbus</option><option value="bacnet">BACnet</option><option value="unknown">I don't know</option></select><button class="btn primary" id="checkCompatibility" type="button">Find Safe Path</button></div><pre id="compatibilityOut" class="checkout-result" style="display:block;min-height:72px">Choose a device class and protocol.</pre></section>
  <section class="card ok full" style="margin-top:16px"><h3>Trust Policy</h3><p>Nearby devices are ignored unless an authenticated adapter exposes them. Adapter discovery still does not grant control. Approval requires an owned Home and a bound source. Locks, alarms, garages, sirens, cameras, and other sensitive actions keep their existing safety gates.</p></section>
  <script src="/js/smart-home-trust-center.js" defer></script>`;
}

export function ambientLifeOsPage() {
  return `${sectionHero('WISDO Ambient Life OS', 'Coordinate home, rooms, household roles, workstations, trading controls, modes, policies, and truth receipts as one mission system. Every mission can be simulated before execution.', '<span class="tag">V23</span><span class="tag">Simulation first</span><span class="tag">Truth ledger</span>')}
  <nav class="actions" aria-label="Ambient Life sections"><a class="btn" href="/app/settings">All settings</a><a class="btn" href="/app/smart-home">Homes & devices</a><a class="btn" href="#rooms">Rooms & privacy</a><a class="btn" href="#household">Household</a><a class="btn" href="#missions">Modes & missions</a><a class="btn" href="#policies">House laws</a><a class="btn" href="#truth">Truth ledger</a></nav><p id="ambientHomeStatus" role="status">Loading your homes…</p>
  <div class="grid"><section class="card"><h3>Missions</h3><div class="metric" id="missionCount">—</div><div class="muted">Cross-domain mission definitions</div></section><section class="card"><h3>Zones</h3><div class="metric" id="zoneCount">—</div><div class="muted">Room/privacy zones</div></section><section class="card"><h3>Household</h3><div class="metric" id="householdCount">—</div><div class="muted">Active permission identities</div></section><section class="card"><h3>Recent Runs</h3><div class="metric" id="runCount">—</div><div class="muted">Truth-tracked executions</div></section></div>
  <div class="grid2" style="margin-top:16px">
    <section class="card" id="missions"><h3>Modes & Mission Composer</h3><p>Create a mission that can coordinate WISDO modes, Home Assistant scenes, your workstation, and supported trading controls. Simulation still decides what is actually allowed.</p><input id="missionName" placeholder="Start My Trading Day"><textarea id="missionDescription" rows="2" placeholder="What should this mission accomplish?"></textarea><label>Home<select id="missionHomeId" data-ambient-home><option value="">Choose a home</option></select></label><div class="row"><select id="missionMode"><option value="trading">Trading</option><option value="focus">Focus</option><option value="family">Family</option><option value="relax">Relax</option><option value="sleep">Sleep</option><option value="away">Away</option><option value="guest">Guest</option></select><input id="missionScene" placeholder="Optional Home Assistant scene alias"></div><input id="missionAccount" placeholder="Optional trading account ID"><label><input id="missionWorkstation" type="checkbox"> Prepare trading workstation</label><br><label><input id="missionPauseTrading" type="checkbox"> Pause new trading entries</label><div style="margin-top:10px"><button class="btn primary" id="createMission" type="button">Create Mission</button></div></section>
    <section class="card"><h3>Mission Simulation / Execution</h3><pre id="missionOutput" class="checkout-result" style="display:block;min-height:290px;max-height:420px;overflow:auto">Select a mission below and simulate it before execution.</pre></section>
  </div>
  <div class="grid2" style="margin-top:16px">
    <section class="card" id="rooms"><h3>Room & Privacy Zones</h3><p>Privacy levels label room sensitivity. They do not physically disable microphones or cameras.</p><div class="row"><label>Home<select id="zoneHomeId" data-ambient-home><option value="">Choose a home</option></select></label><input id="zoneName" placeholder="Trading Room"></div><div class="row"><select id="zonePrivacy"><option value="1">Privacy 1 · Normal</option><option value="2">Privacy 2</option><option value="3">Privacy 3</option><option value="4">Privacy 4</option><option value="5">Privacy 5 · Restricted</option></select><button class="btn" id="createZone" type="button">Add Zone</button></div><div id="zonesList" style="margin-top:10px"></div></section>
    <section class="card" id="household"><h3>Household Permissions</h3><p>These records define mission roles; they do not enroll a voice identity or grant website login access. Guest and technician records require an expiry here.</p><div class="row"><label>Home<select id="memberHomeId" data-ambient-home><option value="">Choose a home</option></select></label><input id="memberName" placeholder="Display name"></div><label>Access expires (your local time)<input id="memberExpires" type="datetime-local"></label><div class="row"><select id="memberRole"><option>ADULT</option><option>CHILD</option><option>GUEST</option><option>TECHNICIAN</option></select><button class="btn" id="addHousehold" type="button">Add Member</button></div><div id="householdList" style="margin-top:10px"></div></section>
  </div>
  <section class="card full" style="margin-top:16px"><h3>Mission Library</h3><p class="muted">A mission can be simulated without touching any device. Running still enforces Home ownership, approved devices, role permissions, physical-security confirmation, trading authorization, and adapter availability.</p><div id="missionsList">Loading…</div></section>
  <section class="card full" id="policies" style="margin-top:16px"><h3>House Laws / Policy Guardrails</h3><p>Baseline policies always apply. Add a rule that blocks an action or requires confirmation.</p><form id="ambientPolicyForm"><label>Home<select id="policyHomeId" data-ambient-home required><option value="">Choose a home</option></select></label><label>Rule name<input id="policyName" maxlength="120" required></label><label>Rule<select id="policyPreset"><option value="security">Never unlock, disarm or open through missions</option><option value="camera">Block camera actions through missions</option><option value="trading">Require confirmation for trading steps</option><option value="home">Require confirmation for all home steps</option></select></label><button class="btn" type="submit">Save house rule</button><p id="policyStatus" role="status"></p></form><div id="policyList">Loading…</div></section>
  <section class="card full" id="truth" style="margin-top:16px"><h3>Truth Ledger</h3><p class="muted">WISDO records simulation, blocked states, confirmation requirements, queued actions, failures, and completions separately. Queued is never presented as physically completed.</p><div id="truthList">Loading…</div></section>
  <section class="card warn full" id="offline" style="margin-top:16px"><h3>Local-First Status</h3><p>V23 can compile safe home-only missions into signed local manifests. The offline edge runner is deliberately not enabled yet, so a manifest is never presented as active offline automation until that runner is built and verified.</p></section>
  <script src="/js/ambient-life-os.js?v=23.1" defer></script>`;
}
