import { getSessionUser, safeReturnPath } from './security.js';
import { ensureLivingOsState,getLivingUser,livingSnapshot,createMission,updateMission,saveWorkspace,createAutomation,updateAutomation,rememberAiObservation,pairDevice,addTimeline } from '../services/livingOperatingSystemService.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const bool=v=>v===true||['1','true','yes','on'].includes(String(v||'').toLowerCase());
function user(req){const s=getSessionUser(req);if(s?.id)return s;if((process.env.NODE_ENV==='test'||bool(process.env.WISDO_ALLOW_TEST_IDENTITY))&&req.headers['x-wisdo-test-user'])return{id:String(req.headers['x-wisdo-test-user']),username:'Test Member',roles:['admin']};return null;}
function auth(req,res,next){const u=user(req);if(!u){if(String(req.headers.accept||'').includes('text/html'))return res.redirect(`/login?returnTo=${encodeURIComponent(safeReturnPath(req.originalUrl,'/app/nexus'))}`);return res.status(401).json({ok:false,error:'Authentication required.'});}req.wisdoUser=u;next();}
async function mutate(load,save,fn){const state=ensureLivingOsState(await load());const result=await fn(state);await save(state);return result;}
function apiScript(){return `<script>async function api(url,o={}){const r=await fetch(url,{headers:{'content-type':'application/json'},...o});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}function msg(t){const e=document.getElementById('msg');if(e)e.textContent=t}async function completeMission(id,target){try{await api('/api/living-os/missions/'+id,{method:'PATCH',body:JSON.stringify({progress:target,status:'completed'})});location.reload()}catch(e){msg(e.message)}}async function toggleRule(id,enabled){await api('/api/living-os/automations/'+id,{method:'PATCH',body:JSON.stringify({enabled})});location.reload()}</script>`;}
function css(){return `<style>:root{--bg:#050b14;--card:#0c1728;--line:#22364f;--green:#39ff88;--cyan:#56d9ff;--gold:#f5c542;--muted:#91a4bd}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#0b2a28 0,transparent 32%),var(--bg);color:#f4f8ff;font-family:Inter,Arial,sans-serif}.wrap{max-width:1280px;margin:auto;padding:26px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.brand{font-weight:900;font-size:22px}.brand b{color:var(--green)}nav{display:flex;gap:8px;flex-wrap:wrap}a,.btn{color:#fff;text-decoration:none;border:1px solid var(--line);background:#0b1524;border-radius:11px;padding:10px 13px;display:inline-block;cursor:pointer}.btn.primary{background:var(--green);color:#021008;border-color:var(--green);font-weight:900}.hero,.card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(17,31,53,.95),rgba(7,15,27,.95));border-radius:22px;box-shadow:0 18px 70px #0007}.hero{padding:27px;margin:22px 0}.hero h1{font-size:clamp(34px,5vw,64px);line-height:.95;letter-spacing:-.055em;margin:8px 0}.kicker{color:var(--cyan);text-transform:uppercase;letter-spacing:.17em;font-size:11px;font-weight:900}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.card{padding:18px}.span4{grid-column:span 4}.span6{grid-column:span 6}.span8{grid-column:span 8}.span12{grid-column:span 12}.score{font-size:60px;font-weight:900;color:var(--green)}.metric{font-size:26px;font-weight:900}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;border-bottom:1px solid #ffffff12;padding:12px 0}.row:last-child{border:0}.chip{padding:6px 9px;border-radius:999px;background:#ffffff0d;color:var(--muted);font-size:11px}.bar{height:8px;background:#ffffff12;border-radius:99px;overflow:hidden}.bar span{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),var(--green))}input,select,textarea{width:100%;background:#07111f;color:white;border:1px solid var(--line);border-radius:10px;padding:11px;margin:6px 0 10px}button{font:inherit}.timeline{border-left:2px solid #29425d;padding-left:18px}.event{position:relative;padding:0 0 18px}.event:before{content:'';position:absolute;width:10px;height:10px;border-radius:50%;background:var(--green);left:-24px;top:5px;box-shadow:0 0 16px var(--green)}@media(max-width:850px){.span4,.span6,.span8{grid-column:span 12}.wrap{padding:14px}}</style>`;}
function nav(){return `<nav><a href="/app/nexus">Nexus</a><a href="/app/missions">Missions</a><a href="/app/workspaces">Workspaces</a><a href="/app/timeline">Timeline</a><a href="/app/automation">Automation</a><a href="/app/culture-score">Culture Score</a><a href="/app/ai-memory">AI Memory</a><a href="/app/devices">Devices</a><a href="/app/ecosystem-map">Ecosystem</a><a href="/app/dashboard">Classic Dashboard</a></nav>`;}
function shell(title,body){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Wisdo Living OS</title>${css()}</head><body><div class="wrap"><div class="top"><a class="brand" href="/app/nexus">WISDO <b>Living OS</b></a>${nav()}</div>${body}<p id="msg" class="muted"></p></div>${apiScript()}</body></html>`;}
function scoreBars(score){return ['health','discipline','consistency','learning','community','growth'].map(k=>`<div style="margin:12px 0"><div class="row"><span>${esc(k[0].toUpperCase()+k.slice(1))}</span><strong>${score[k]}</strong></div><div class="bar"><span style="width:${score[k]}%"></span></div></div>`).join('');}
function nexusPage(s,u){const b=s.briefing;return `<section class="hero"><div class="kicker">Nexus Daily Command Briefing</div><h1>${esc(b.greeting)}, ${esc(u.global_name||u.username||'Member')}.</h1><p class="muted">${esc(b.summary)} ${esc(b.aiSummary)}</p><div><a class="btn primary" href="${esc(b.workspace?.path||'/app/dashboard')}">Resume ${esc(b.workspace?.name||'Workspace')}</a> <a class="btn" href="/app/missions">Open today’s missions</a></div></section><div class="grid"><section class="card span4"><div class="kicker">Culture Score</div><div class="score">${b.score.overall}</div><p class="muted">A balanced measure of system health, discipline, learning and growth.</p><a href="/app/culture-score">View breakdown</a></section><section class="card span8"><div class="kicker">Active Missions</div>${b.activeMissions.map(m=>`<div class="row"><div><strong>${esc(m.title)}</strong><div class="muted">${m.progress}/${m.target} · +${m.rewardXp} XP</div></div><a href="${esc(m.href)}">Continue</a></div>`).join('')||'<p class="muted">No active missions.</p>'}</section><section class="card span4"><div class="kicker">Operating Memory</div><div class="metric">${s.timeline.length}</div><p class="muted">Timeline events retained</p><div class="metric">${s.aiMemory.observations.length}</div><p class="muted">AI observations learned</p></section><section class="card span4"><div class="kicker">Automation</div><div class="metric">${s.automations.filter(x=>x.enabled).length}</div><p class="muted">Rules active</p><a href="/app/automation">Open Automation Studio</a></section><section class="card span4"><div class="kicker">Device Ecosystem</div><div class="metric">${s.devices.length}</div><p class="muted">Paired Culture devices</p><a href="/app/devices">Open Device Hub</a></section><section class="card span12"><div class="kicker">Recent Timeline</div>${s.timeline.slice(0,5).map(e=>`<div class="row"><div><strong>${esc(e.title)}</strong><div class="muted">${esc(e.detail)}</div></div><span class="chip">${new Date(e.at).toLocaleString()}</span></div>`).join('')}</section></div>`;}
function missionsPage(s){return `<section class="hero"><div class="kicker">Mission Engine</div><h1>Always know what comes next.</h1><p class="muted">Complete missions to build Experience Rank, Culture Credits, discipline and platform mastery.</p></section><div class="grid"><section class="card span8">${s.missions.map(m=>`<div class="row"><div style="flex:1"><strong>${esc(m.title)}</strong><div class="muted">${esc(m.description||m.category)} · Reward: ${m.rewardXp} XP + ${m.rewardCredits} credits</div><div class="bar" style="margin-top:8px"><span style="width:${Math.min(100,m.progress/m.target*100)}%"></span></div></div><div>${m.status==='completed'?'<span class="chip">Completed</span>':`<button class="btn primary" onclick="completeMission('${m.id}',${m.target})">Complete</button>`}</div></div>`).join('')}</section><section class="card span4"><h2>Create mission</h2><form method="post" action="/living-os/missions"><input name="title" placeholder="Mission title" required><select name="category"><option>personal</option><option>trading</option><option>education</option><option>community</option></select><input name="rewardXp" type="number" value="100"><button class="btn primary">Create Mission</button></form></section></div>`;}
function workspacesPage(s){return `<section class="hero"><div class="kicker">Workspace Engine</div><h1>Restore your complete operating context.</h1></section><div class="grid">${s.workspaces.map(w=>`<section class="card span4"><div class="metric">${esc(w.icon)}</div><h2>${esc(w.name)}</h2><p class="muted">Mode: ${esc(w.mode)} · ${esc(w.path)}</p><a class="btn primary" href="${esc(w.path)}${w.accountId?`?accountId=${encodeURIComponent(w.accountId)}`:''}">Launch</a></section>`).join('')}<section class="card span12"><h2>Save current workspace</h2><form method="post" action="/living-os/workspaces"><div class="grid"><div class="span4"><input name="name" placeholder="Workspace name" required></div><div class="span4"><input name="path" value="/app/dashboard"></div><div class="span4"><select name="mode"><option>focus</option><option>teach</option><option>build</option><option>harvest</option></select></div></div><button class="btn primary">Save Workspace</button></form></section></div>`;}
function timelinePage(s){return `<section class="hero"><div class="kicker">Wisdo Timeline</div><h1>Your journey becomes permanent memory.</h1></section><section class="card timeline">${s.timeline.map(e=>`<div class="event"><strong>${esc(e.title)}</strong><div class="muted">${esc(e.detail)}</div><small class="muted">${new Date(e.at).toLocaleString()} · ${esc(e.type)}</small></div>`).join('')}</section>`;}
function automationPage(s){return `<section class="hero"><div class="kicker">Automation Studio</div><h1>When this happens, Wisdo acts.</h1><p class="muted">Rules are stored now; execution adapters can safely connect to copier, email, Discord and Harvest services.</p></section><div class="grid"><section class="card span8">${s.automations.map(r=>`<div class="row"><div><strong>${esc(r.name)}</strong><div class="muted">IF ${esc(r.trigger)} ${esc(r.operator)} ${esc(r.value)} → ${esc(r.action)}</div></div><button class="btn" onclick="toggleRule('${r.id}',${!r.enabled})">${r.enabled?'Disable':'Enable'}</button></div>`).join('')||'<p class="muted">No automation rules yet.</p>'}</section><section class="card span4"><h2>Create rule</h2><form method="post" action="/living-os/automations"><input name="name" placeholder="Rule name"><select name="trigger"><option>reporter_offline</option><option>drawdown_above</option><option>profit_above</option><option>mission_completed</option><option>account_connected</option><option>daily_time</option></select><input name="value" placeholder="Threshold"><select name="action"><option>notify_dashboard</option><option>notify_discord</option><option>notify_email</option><option>pause_copier</option><option>activate_harvest</option><option>set_mode</option><option>create_mission</option></select><button class="btn primary">Create Automation</button></form></section></div>`;}
function memoryPage(s){return `<section class="hero"><div class="kicker">Personal AI Memory</div><h1>Wisdo learns how you operate.</h1><p class="muted">${esc(s.aiMemory.lastSummary)}</p></section><div class="grid"><section class="card span8">${s.aiMemory.observations.map(o=>`<div class="row"><div><strong>${esc(o.text)}</strong><div class="muted">${esc(o.category)}</div></div><span class="chip">${o.confidence}% confidence</span></div>`).join('')||'<p class="muted">No observations yet.</p>'}</section><section class="card span4"><h2>Teach Wisdo</h2><form method="post" action="/living-os/memory"><textarea name="text" placeholder="Example: I perform best on XAUUSD during London session." required></textarea><select name="category"><option>pattern</option><option>preference</option><option>risk</option><option>learning</option></select><button class="btn primary">Remember</button></form></section></div>`;}
function devicesPage(s){return `<section class="hero"><div class="kicker">Device Hub</div><h1>Software ready for Culture hardware.</h1></section><div class="grid"><section class="card span8">${s.devices.map(d=>`<div class="row"><div><strong>${esc(d.name)}</strong><div class="muted">${esc(d.type)} · Firmware ${esc(d.firmware)}</div></div><span class="chip">${d.status}</span></div>`).join('')||'<p class="muted">No Culture devices paired.</p>'}</section><section class="card span4"><h2>Pair prototype</h2><form method="post" action="/living-os/devices"><input name="name" placeholder="Device name" required><select name="type"><option>culture_band</option><option>wisdo_home</option><option>culture_dock</option><option>ar_glass</option><option>prototype</option></select><input name="firmware" value="alpha-1"><button class="btn primary">Pair Device</button></form></section></div>`;}
function mapPage(){return `<section class="hero"><div class="kicker">Ecosystem Map</div><h1>See how every part of Wisdo connects.</h1></section><div class="grid">${[['Culture Identity','/app/presence'],['Nexus Intelligence','/app/nexus'],['Trading Accounts','/app/connect-account'],['Culture Lanes','/app/copier-engine'],['Bots','/member/my-bots'],['Academy','/app/education'],['Automation','/app/automation'],['Culture Band','/app/devices'],['Wisdo Home','/app/devices']].map(([n,h],i)=>`<section class="card span4"><div class="kicker">Layer ${i+1}</div><h2>${n}</h2><a href="${h}">Open module →</a></section>`).join('')}</div>`;}

export function registerLivingOperatingSystemRoutes(app,{loadEcosystemState,saveEcosystemState}){
  app.get('/api/living-os/me',auth,async(req,res)=>{const state=ensureLivingOsState(await loadEcosystemState());const snap=livingSnapshot(state,req.wisdoUser);await saveEcosystemState(state);res.json({ok:true,...snap});});
  app.post('/api/living-os/missions',auth,async(req,res)=>res.status(201).json({ok:true,mission:await mutate(loadEcosystemState,saveEcosystemState,s=>createMission(s,req.wisdoUser,req.body||{}))}));
  app.patch('/api/living-os/missions/:id',auth,async(req,res)=>{try{res.json({ok:true,mission:await mutate(loadEcosystemState,saveEcosystemState,s=>updateMission(s,req.wisdoUser,req.params.id,req.body||{}))});}catch(e){res.status(404).json({ok:false,error:e.message});}});
  app.post('/api/living-os/workspaces',auth,async(req,res)=>res.status(201).json({ok:true,workspace:await mutate(loadEcosystemState,saveEcosystemState,s=>saveWorkspace(s,req.wisdoUser,req.body||{}))}));
  app.post('/api/living-os/automations',auth,async(req,res)=>res.status(201).json({ok:true,automation:await mutate(loadEcosystemState,saveEcosystemState,s=>createAutomation(s,req.wisdoUser,req.body||{}))}));
  app.patch('/api/living-os/automations/:id',auth,async(req,res)=>{try{res.json({ok:true,automation:await mutate(loadEcosystemState,saveEcosystemState,s=>updateAutomation(s,req.wisdoUser,req.params.id,req.body||{}))});}catch(e){res.status(404).json({ok:false,error:e.message});}});
  app.post('/api/living-os/memory',auth,async(req,res)=>res.status(201).json({ok:true,memory:await mutate(loadEcosystemState,saveEcosystemState,s=>rememberAiObservation(s,req.wisdoUser,req.body||{}))}));
  app.post('/api/living-os/devices',auth,async(req,res)=>res.status(201).json({ok:true,device:await mutate(loadEcosystemState,saveEcosystemState,s=>pairDevice(s,req.wisdoUser,req.body||{}))}));
  app.post('/api/living-os/timeline',auth,async(req,res)=>res.status(201).json({ok:true,event:await mutate(loadEcosystemState,saveEcosystemState,s=>addTimeline(s,req.wisdoUser,req.body||{}))}));
  const forms={
    '/living-os/missions':(s,u,b)=>createMission(s,u,b),'/living-os/workspaces':(s,u,b)=>saveWorkspace(s,u,b),'/living-os/automations':(s,u,b)=>createAutomation(s,u,b),'/living-os/memory':(s,u,b)=>rememberAiObservation(s,u,b),'/living-os/devices':(s,u,b)=>pairDevice(s,u,b)
  };
  for(const [path,fn] of Object.entries(forms))app.post(path,auth,async(req,res)=>{await mutate(loadEcosystemState,saveEcosystemState,s=>fn(s,req.wisdoUser,req.body||{}));const back={ '/living-os/missions':'/app/missions','/living-os/workspaces':'/app/workspaces','/living-os/automations':'/app/automation','/living-os/memory':'/app/ai-memory','/living-os/devices':'/app/devices'}[path];res.redirect(back);});
  const pages={nexus:nexusPage,missions:missionsPage,workspaces:workspacesPage,timeline:timelinePage,automation:automationPage,'culture-score':s=>`<section class="hero"><div class="kicker">Culture Score</div><h1>Your growth, measured as a whole.</h1></section><div class="grid"><section class="card span4"><div class="score">${s.score.overall}</div><p class="muted">Overall Culture Score</p></section><section class="card span8">${scoreBars(s.score)}</section></div>`,'ai-memory':memoryPage,devices:devicesPage,'ecosystem-map':mapPage};
  for(const [name,render] of Object.entries(pages))app.get(`/app/${name}`,auth,async(req,res)=>{const state=ensureLivingOsState(await loadEcosystemState());const snap=livingSnapshot(state,req.wisdoUser);await saveEcosystemState(state);res.type('html').send(shell(name==='nexus'?'Nexus Command Center':name.replaceAll('-',' '),render(snap,req.wisdoUser)));});
  app.get('/app/daily-briefing',auth,(req,res)=>res.redirect('/app/nexus'));
}
